package com.taemoi.project.controllers;

import java.time.*; import java.util.*; import java.util.concurrent.*;
import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
import org.springframework.data.domain.*;
import com.taemoi.project.dtos.request.*; import com.taemoi.project.entities.*; import com.taemoi.project.services.*; import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid;

@RestController @RequestMapping("/api/preinscripciones")
public class PreinscripcionController {
 private final PreinscripcionService service; private final TemporadaService temporadas; private final ConcurrentMap<String,Deque<Instant>> intentos=new ConcurrentHashMap<>();
 public PreinscripcionController(PreinscripcionService s,TemporadaService t){service=s;temporadas=t;}
 @PostMapping public ResponseEntity<?> crear(@Valid @RequestBody PreinscripcionRequest body,HttpServletRequest request){limitar(request);return ResponseEntity.status(HttpStatus.CREATED).body(service.crear(body));}
 @GetMapping("/public/temporada") public Map<String,String> temporada(){return Map.of("temporada",temporadas.actual());}
 @GetMapping("/public/configuracion/{deporte}") public Map<String,Object> configuracion(@PathVariable Deporte deporte){return service.configuracion(deporte);}
 @GetMapping("/public/grupos/{deporte}") public List<Map<String,Object>> grupos(@PathVariable Deporte deporte){return service.grupos(deporte);}
 @GetMapping("/public/turnos/{deporte}") public List<Map<String,Object>> turnos(@PathVariable Deporte deporte){return service.turnos(deporte);}
 @GetMapping("/{referencia}/documento") public ResponseEntity<byte[]> documento(@PathVariable String referencia,@RequestParam String token){return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=preinscripcion-"+referencia+".pdf").body(service.documento(referencia,token));}
 @GetMapping("/{referencia}/documento-firmado") @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public ResponseEntity<byte[]> documentoFirmado(@PathVariable String referencia){Preinscripcion p=service.buscar(referencia);return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=preinscripcion-"+referencia+".pdf").body(p.getPdfFirmado());}
 @GetMapping("/{referencia}/firma") @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public ResponseEntity<byte[]> firma(@PathVariable String referencia){return ResponseEntity.ok().contentType(MediaType.IMAGE_PNG).cacheControl(CacheControl.noStore()).body(service.buscar(referencia).getFirma());}
 @GetMapping @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public Map<String,Object> listar(@RequestParam(required=false) String temporada,@RequestParam(required=false) Deporte deporte,@RequestParam(required=false) EstadoPreinscripcion estado,@RequestParam(required=false) String q,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="25") int size){int pagina=Math.max(0,page),tamano=Math.min(100,Math.max(1,size));Page<Preinscripcion> resultado=service.listar(temporada,deporte,estado,q,PageRequest.of(pagina,tamano,Sort.by(Sort.Order.desc("creadaEn"),Sort.Order.desc("id"))));return Map.of("content",resultado.getContent().stream().map(this::resumen).toList(),"page",resultado.getNumber(),"size",resultado.getSize(),"totalElements",resultado.getTotalElements(),"totalPages",resultado.getTotalPages(),"first",resultado.isFirst(),"last",resultado.isLast());}
 @GetMapping("/{referencia}") @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public Map<String,Object> detalle(@PathVariable String referencia){Preinscripcion p=service.buscar(referencia);Map<String,Object> m=new LinkedHashMap<>(resumen(p));m.put("turno",p.getTurnoSnapshot());m.put("consentimientoFotografico",p.getConsentimientoFotografico());m.put("plantillaSnapshot",p.getPlantillaSnapshot());m.put("alumnoExistente",p.getAlumno()==null?null:p.getAlumno().getId());return m;}
 @PostMapping("/{referencia}/cancelar") @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public void cancelar(@PathVariable String referencia){service.cancelar(referencia);}
 @DeleteMapping("/{referencia}") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasAuthority('ROLE_ADMIN')") public void eliminar(@PathVariable String referencia){service.eliminar(referencia);}
 @PostMapping("/{referencia}/reenviar") @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public void reenviar(@PathVariable String referencia){service.reenviar(referencia);}
 @PostMapping("/{referencia}/finalizar") @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public void finalizar(@PathVariable String referencia,@Valid @RequestBody FinalizarPreinscripcionRequest body){service.finalizar(referencia,body);}
 @GetMapping("/plantillas/{deporte}") @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public Map<String,Object> plantillas(@PathVariable Deporte deporte){return service.plantillas(deporte);}
 @PostMapping("/plantillas/{deporte}") @PreAuthorize("hasAuthority('ROLE_ADMIN')") public Map<String,Object> plantilla(@PathVariable Deporte deporte,@Valid @RequestBody PlantillaPreinscripcionRequest body){return service.nuevaPlantilla(deporte,body);}
 @PostMapping(value="/plantillas/{deporte}/preview",produces=MediaType.APPLICATION_PDF_VALUE) @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public byte[] preview(@PathVariable Deporte deporte,@Valid @RequestBody PlantillaPreinscripcionRequest body){return service.preview(deporte,body);}
 @PostMapping("/plantillas/{deporte}/{version}/restaurar") @PreAuthorize("hasAuthority('ROLE_ADMIN')") public Map<String,Object> restaurar(@PathVariable Deporte deporte,@PathVariable Integer version){return service.restaurar(deporte,version);}
 private Map<String,Object> resumen(Preinscripcion p){Map<String,Object> m=new LinkedHashMap<>();m.put("referencia",p.getReferencia());m.put("temporada",p.getTemporada());m.put("deporte",p.getDeporte());m.put("estado",p.getEstado());m.put("posicionListaEspera",service.posicionListaEspera(p));m.put("nombre",p.getNombre());m.put("apellidos",p.getApellidos());m.put("dni",p.getDni());m.put("fechaNacimiento",p.getFechaNacimiento());m.put("direccion",p.getDireccion());m.put("telefono",p.getTelefono());m.put("telefono2",p.getTelefono2());m.put("email",p.getEmail());m.put("tieneDiscapacidad",p.getTieneDiscapacidad());m.put("tutorNombre",p.getTutorNombre());m.put("tutorDni",p.getTutorDni());m.put("grupo",p.getGrupoSnapshot()!=null?p.getGrupoSnapshot():p.getTurnoSnapshot());m.put("turnosSolicitados",service.turnosSolicitados(p));m.put("creadaEn",p.getCreadaEn());m.put("emailEnviado",p.getEmailEnviado());m.put("emailIntentos",p.getEmailIntentos());m.put("alumnosCoincidentes",service.alumnosCoincidentes(p));return m;}
 private void limitar(HttpServletRequest r){String ip=Optional.ofNullable(r.getHeader("X-Forwarded-For")).orElse(r.getRemoteAddr()).split(",")[0];Instant corte=Instant.now().minus(Duration.ofMinutes(10));Deque<Instant> d=intentos.computeIfAbsent(ip,k->new ConcurrentLinkedDeque<>());while(!d.isEmpty()&&d.peekFirst().isBefore(corte))d.pollFirst();if(d.size()>=5)throw new IllegalStateException("Demasiados intentos. Espera unos minutos.");d.addLast(Instant.now());}
}
