package com.taemoi.project.controllers;

import java.time.*; import java.util.*; import java.util.concurrent.*;
import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
import com.taemoi.project.dtos.request.*; import com.taemoi.project.entities.*; import com.taemoi.project.services.*; import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid;

@RestController @RequestMapping("/api/preinscripciones")
public class PreinscripcionController {
 private final PreinscripcionService service; private final TemporadaService temporadas; private final ConcurrentMap<String,Deque<Instant>> intentos=new ConcurrentHashMap<>();
 public PreinscripcionController(PreinscripcionService s,TemporadaService t){service=s;temporadas=t;}
 @PostMapping public ResponseEntity<?> crear(@Valid @RequestBody PreinscripcionRequest body,HttpServletRequest request){limitar(request);return ResponseEntity.status(HttpStatus.CREATED).body(service.crear(body));}
 @GetMapping("/public/temporada") public Map<String,String> temporada(){return Map.of("temporada",temporadas.actual());}
 @GetMapping("/public/configuracion/{deporte}") public Map<String,Object> configuracion(@PathVariable Deporte deporte){return service.configuracion(deporte);}
 @GetMapping("/public/grupos/{deporte}") public List<Map<String,Object>> grupos(@PathVariable Deporte deporte){return service.grupos(deporte);}
 @GetMapping("/public/turnos/{deporte}") public List<Map<String,Object>> turnos(@PathVariable Deporte deporte){return service.turnos(deporte);}
 @GetMapping("/{referencia}/documento") public ResponseEntity<byte[]> documento(@PathVariable String referencia,@RequestParam String token){return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=preinscripcion-"+referencia+".pdf").body(service.documento(referencia,token));}
 @GetMapping @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public List<Map<String,Object>> listar(@RequestParam(required=false) String temporada,@RequestParam(required=false) Deporte deporte,@RequestParam(required=false) EstadoPreinscripcion estado,@RequestParam(required=false) String q){String query=q==null?"":q.trim().toUpperCase();return service.listar().stream().filter(p->temporada==null||temporada.equals(p.getTemporada())).filter(p->deporte==null||deporte==p.getDeporte()).filter(p->estado==null||estado==p.getEstado()).filter(p->query.isBlank()||p.getDni().contains(query)||p.getReferencia().contains(query)).map(this::resumen).toList();}
 @GetMapping("/{referencia}") @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public Map<String,Object> detalle(@PathVariable String referencia){Preinscripcion p=service.buscar(referencia);Map<String,Object> m=new LinkedHashMap<>(resumen(p));m.put("direccion",p.getDireccion());m.put("telefono",p.getTelefono());m.put("email",p.getEmail());m.put("tutorNombre",p.getTutorNombre());m.put("tutorDni",p.getTutorDni());m.put("grupo",p.getGrupoSnapshot()!=null?p.getGrupoSnapshot():p.getTurnoSnapshot());m.put("turno",p.getTurnoSnapshot());m.put("consentimientoFotografico",p.getConsentimientoFotografico());m.put("plantillaSnapshot",p.getPlantillaSnapshot());m.put("alumnoExistente",p.getAlumno()==null?null:p.getAlumno().getId());return m;}
 @PostMapping("/{referencia}/cancelar") @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public void cancelar(@PathVariable String referencia){service.cancelar(referencia);}
 @PostMapping("/{referencia}/reenviar") @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public void reenviar(@PathVariable String referencia){service.reenviar(referencia);}
 @PostMapping("/{referencia}/finalizar") @PreAuthorize("hasAnyAuthority('ROLE_ADMIN','ROLE_MANAGER')") public void finalizar(@PathVariable String referencia,@Valid @RequestBody FinalizarPreinscripcionRequest body){service.finalizar(referencia,body);}
 @PostMapping("/plantillas/{deporte}") @PreAuthorize("hasAuthority('ROLE_ADMIN')") public Map<String,Object> plantilla(@PathVariable Deporte deporte,@RequestBody Map<String,String> body){PlantillaPreinscripcion p=service.nuevaPlantilla(deporte,body.get("contenido"),body.getOrDefault("instrucciones",""));return Map.of("id",p.getId(),"version",p.getVersion());}
 private Map<String,Object> resumen(Preinscripcion p){Map<String,Object> m=new LinkedHashMap<>();m.put("referencia",p.getReferencia());m.put("temporada",p.getTemporada());m.put("deporte",p.getDeporte());m.put("estado",p.getEstado());m.put("nombre",p.getNombre());m.put("apellidos",p.getApellidos());m.put("dni",p.getDni());m.put("fechaNacimiento",p.getFechaNacimiento());m.put("grupo",p.getGrupoSnapshot()!=null?p.getGrupoSnapshot():p.getTurnoSnapshot());m.put("creadaEn",p.getCreadaEn());m.put("emailEnviado",p.getEmailEnviado());m.put("emailIntentos",p.getEmailIntentos());return m;}
 private void limitar(HttpServletRequest r){String ip=Optional.ofNullable(r.getHeader("X-Forwarded-For")).orElse(r.getRemoteAddr()).split(",")[0];Instant corte=Instant.now().minus(Duration.ofMinutes(10));Deque<Instant> d=intentos.computeIfAbsent(ip,k->new ConcurrentLinkedDeque<>());while(!d.isEmpty()&&d.peekFirst().isBefore(corte))d.pollFirst();if(d.size()>=5)throw new IllegalStateException("Demasiados intentos. Espera unos minutos.");d.addLast(Instant.now());}
}
