export enum TipoTarifa {
  PILATES = 'PILATES',
  DEFENSA_PERSONAL_FEMENINA = 'DEFENSA_PERSONAL_FEMENINA',
  ADULTO = 'ADULTO',
  ADULTO_GRUPO = 'ADULTO_GRUPO',
  FAMILIAR = 'FAMILIAR',
  INFANTIL = 'INFANTIL',
  INFANTIL_GRUPO = 'INFANTIL_GRUPO',
  HERMANOS = 'HERMANOS',
  PADRES_HIJOS = 'PADRES_HIJOS'
}
