export enum TipoTarifa {
  // Tarifas para Taekwondo
  ADULTO = 'ADULTO',
  ADULTO_GRUPO = 'ADULTO_GRUPO',
  FAMILIAR = 'FAMILIAR',
  INFANTIL = 'INFANTIL',
  INFANTIL_GRUPO = 'INFANTIL_GRUPO',
  HERMANOS = 'HERMANOS',
  PADRES_HIJOS = 'PADRES_HIJOS',

  // Tarifas para Kickboxing
  KICKBOXING_PADRES_HIJOS = 'KICKBOXING_PADRES_HIJOS',
  KICKBOXING_HERMANOS = 'KICKBOXING_HERMANOS',
  KICKBOXING_FAMILIAR = 'KICKBOXING_FAMILIAR',

  // Tarifas para otras actividades
  PILATES = 'PILATES',
  DEFENSA_PERSONAL_FEMENINA = 'DEFENSA_PERSONAL_FEMENINA'
}
