package com.taemoi.project.services;

import java.awt.*; import java.awt.image.BufferedImage; import java.io.*; import java.security.*; import java.time.*; import java.util.*; import javax.imageio.ImageIO;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.fasterxml.jackson.databind.ObjectMapper; import com.taemoi.project.dtos.request.*; import com.taemoi.project.entities.*; import com.taemoi.project.repositories.*;

@Service
public class PreinscripcionService {
 private final PreinscripcionRepository repo; private final PlantillaPreinscripcionRepository plantillas; private final TurnoRepository turnos;
 private final AlumnoRepository alumnos; private final AlumnoDeporteRepository alumnoDeportes; private final TemporadaService temporadas; private final PDFService pdf;
 private final EmailService email; private final ConfiguracionSistemaService configuracion; private final ObjectMapper json;
 public PreinscripcionService(PreinscripcionRepository r,PlantillaPreinscripcionRepository p,TurnoRepository t,AlumnoRepository a,AlumnoDeporteRepository ad,TemporadaService ts,PDFService ps,EmailService es,ConfiguracionSistemaService cs,ObjectMapper om){repo=r;plantillas=p;turnos=t;alumnos=a;alumnoDeportes=ad;temporadas=ts;pdf=ps;email=es;configuracion=cs;json=om;}

 @Transactional public Map<String,Object> crear(PreinscripcionRequest d){
  String dni=d.dni().trim().toUpperCase(Locale.ROOT), temporada=temporadas.actual();
  if(repo.existsByDniAndDeporteAndTemporada(dni,d.deporte(),temporada)) throw new IllegalArgumentException("Ya existe una preinscripción para ese DNI, deporte y temporada.");
  Turno turno=turnos.findById(d.turnoId()).orElseThrow(()->new IllegalArgumentException("Turno no encontrado."));
  if(turno.getGrupo()==null||turno.getGrupo().getDeporte()!=d.deporte()) throw new IllegalArgumentException("El turno no pertenece al deporte seleccionado.");
  if(Period.between(d.fechaNacimiento(),LocalDate.now()).getYears()<18&&(blank(d.tutorNombre())||blank(d.tutorDni()))) throw new IllegalArgumentException("Los menores deben indicar responsable legal y su DNI.");
  byte[] firma=decodificarFirma(d.firmaBase64()); PlantillaPreinscripcion plantilla=plantillas.findFirstByDeporteAndActivaTrueOrderByVersionDesc(d.deporte()).orElseThrow(()->new IllegalStateException("No hay plantilla activa."));
  Preinscripcion p=new Preinscripcion(); p.setReferencia(referencia()); p.setTemporada(temporada); p.setDeporte(d.deporte()); p.setNombre(clean(d.nombre())); p.setApellidos(clean(d.apellidos())); p.setDni(dni); p.setFechaNacimiento(d.fechaNacimiento()); p.setDireccion(clean(d.direccion())); p.setTelefono(clean(d.telefono())); p.setEmail(d.email().trim().toLowerCase(Locale.ROOT)); p.setTutorNombre(clean(d.tutorNombre())); p.setTutorDni(clean(d.tutorDni())); p.setConsentimientoFotografico(d.consentimientoFotografico()); p.setAceptacionNormas(true); p.setFirmanteNombre(clean(d.firmanteNombre())); p.setFirma(firma); p.setTurno(turno); p.setTurnoSnapshot(turno.getGrupo().getNombre()+" · "+turno.getDiaSemana()+" · "+turno.getHoraInicio()+"-"+turno.getHoraFin()); p.setPlantilla(plantilla);
  try{p.setPlantillaSnapshot(json.writeValueAsString(Map.of("version",plantilla.getVersion(),"contenido",plantilla.getContenido(),"instrucciones",plantilla.getInstrucciones())));}catch(Exception e){throw new IllegalStateException(e);}
  String token=UUID.randomUUID().toString().replace("-",""); p.setTokenDocumentoHash(hash(token)); p.setPdfFirmado(pdf.generarPreinscripcionFirmada(p)); repo.save(p); enviar(p);
  return Map.of("referencia",p.getReferencia(),"temporada",p.getTemporada(),"tokenDocumento",token,"emailEnviado",p.getEmailEnviado(),"mensaje","Preinscripción recibida; no equivale a inscripción ni reserva de plaza.");
 }
 public Map<String,Object> configuracion(Deporte deporte){PlantillaPreinscripcion p=plantillas.findFirstByDeporteAndActivaTrueOrderByVersionDesc(deporte).orElseThrow(); return Map.of("deporte",deporte,"version",p.getVersion(),"contenido",parse(p.getContenido()),"instrucciones",p.getInstrucciones());}
 public List<Map<String,Object>> turnos(Deporte deporte){return turnos.findAllWithAlumnos().stream().filter(t->t.getGrupo()!=null&&t.getGrupo().getDeporte()==deporte).map(t->Map.<String,Object>of("id",t.getId(),"deporte",deporte,"grupo",t.getGrupo().getNombre(),"grupoId",t.getGrupo().getId(),"rangoEdadMin",Optional.ofNullable(t.getGrupo().getRangoEdadMin()).orElse(0),"rangoEdadMax",Optional.ofNullable(t.getGrupo().getRangoEdadMax()).orElse(99),"diaSemana",t.getDiaSemana(),"horaInicio",t.getHoraInicio(),"horaFin",t.getHoraFin())).toList();}
 public byte[] documento(String referencia,String token){Preinscripcion p=buscar(referencia); if(!MessageDigest.isEqual(hash(token).getBytes(),p.getTokenDocumentoHash().getBytes()))throw new SecurityException("Token de documento inválido."); return p.getPdfFirmado();}
 public List<Preinscripcion> listar(){return repo.findAll();} public Preinscripcion buscar(String ref){return repo.findByReferencia(ref).orElseThrow(()->new NoSuchElementException("Preinscripción no encontrada."));}
 @Transactional public void cancelar(String ref){Preinscripcion p=buscar(ref); if(p.getEstado()!=EstadoPreinscripcion.PENDIENTE)throw new IllegalStateException("Solo se puede cancelar una solicitud pendiente."); p.setEstado(EstadoPreinscripcion.CANCELADA);p.setCanceladaEn(Instant.now());}
 @Transactional public void reenviar(String ref){enviar(buscar(ref));}
 @Transactional public void finalizar(String ref,FinalizarPreinscripcionRequest d){Preinscripcion p=buscar(ref); if(p.getEstado()!=EstadoPreinscripcion.PENDIENTE)throw new IllegalStateException("La solicitud no está pendiente."); Turno t=p.getTurno(); if(t.getAlumnos().size()>=configuracion.obtenerLimiteTurno())throw new IllegalStateException("El turno seleccionado ya no tiene plazas."); Alumno a=alumnos.findById(d.alumnoId()).orElseThrow(); if(d.actualizarDatos()){a.setNombre(p.getNombre());a.setApellidos(p.getApellidos());a.setNif(p.getDni());a.setDireccion(p.getDireccion());a.setTelefono(Integer.valueOf(p.getTelefono().replaceAll("\\D","")));a.setEmail(p.getEmail());} if(d.reactivar())a.setActivo(true); AlumnoDeporte ad=alumnoDeportes.findByAlumnoIdAndDeporte(a.getId(),p.getDeporte()).orElseGet(()->{AlumnoDeporte n=new AlumnoDeporte();n.setAlumno(a);n.setDeporte(p.getDeporte());return n;}); ad.setActivo(true); alumnoDeportes.save(ad); a.addTurno(t); t.getGrupo().addAlumno(a); alumnos.save(a); p.setAlumno(a);p.setEstado(EstadoPreinscripcion.FINALIZADA);p.setFinalizadaEn(Instant.now());}
 @Transactional public PlantillaPreinscripcion nuevaPlantilla(Deporte deporte,String contenido,String instrucciones){jsonValido(contenido); List<PlantillaPreinscripcion> anteriores=plantillas.findByDeporteOrderByVersionDesc(deporte); anteriores.forEach(x->x.setActiva(false)); PlantillaPreinscripcion p=new PlantillaPreinscripcion();p.setDeporte(deporte);p.setVersion(anteriores.isEmpty()?1:anteriores.get(0).getVersion()+1);p.setActiva(true);p.setContenido(contenido);p.setInstrucciones(clean(instrucciones));return plantillas.save(p);}
 private void enviar(Preinscripcion p){p.setEmailIntentos(p.getEmailIntentos()+1);try{email.sendEmailConAdjunto(p.getEmail(),"Preinscripción "+p.getReferencia(),"<p>Hemos recibido tu preinscripción <strong>"+p.getReferencia()+"</strong>.</p><p>No supone inscripción ni reserva de plaza. El pago y la formalización son presenciales al inicio de la temporada.</p>","preinscripcion-"+p.getReferencia()+".pdf",p.getPdfFirmado());p.setEmailEnviado(true);p.setEmailUltimoError(null);}catch(Exception e){p.setEmailEnviado(false);p.setEmailUltimoError(clean(e.getMessage()));}}
 private byte[] decodificarFirma(String value){try{String b=value.substring(value.indexOf(',')+1);byte[] data=Base64.getDecoder().decode(b);if(data.length<100||data.length>500000)throw new IllegalArgumentException();BufferedImage original=ImageIO.read(new ByteArrayInputStream(data));if(original==null||original.getWidth()>2400||original.getHeight()>1200)throw new IllegalArgumentException();BufferedImage limpia=new BufferedImage(original.getWidth(),original.getHeight(),BufferedImage.TYPE_INT_RGB);Graphics2D g=limpia.createGraphics();g.setColor(Color.WHITE);g.fillRect(0,0,limpia.getWidth(),limpia.getHeight());g.drawImage(original,0,0,null);g.dispose();ByteArrayOutputStream out=new ByteArrayOutputStream();ImageIO.write(limpia,"png",out);return out.toByteArray();}catch(Exception e){throw new IllegalArgumentException("La firma no es una imagen válida o excede 500 KB.");}}
 private String referencia(){return "PRE-"+LocalDate.now().getYear()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();} private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private String clean(String s){return s==null?null:s.replaceAll("[<>]","").trim();} private boolean blank(String s){return s==null||s.isBlank();} private Object parse(String s){try{return json.readTree(s);}catch(Exception e){return s;}} private void jsonValido(String s){try{json.readTree(s);}catch(Exception e){throw new IllegalArgumentException("El contenido debe ser JSON válido.");}}
}
