package com.taemoi.project.services;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.security.MessageDigest;
import java.time.Instant;
import java.time.LocalDate;
import java.time.Period;
import java.util.Comparator;
import java.util.ArrayList;
import java.util.Date;
import java.util.HexFormat;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;

import javax.imageio.ImageIO;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.taemoi.project.dtos.request.ActualizarTurnosPreinscripcionRequest;
import com.taemoi.project.dtos.request.FinalizarPreinscripcionRequest;
import com.taemoi.project.dtos.request.PreinscripcionRequest;
import com.taemoi.project.dtos.request.PlantillaPreinscripcionRequest;
import com.taemoi.project.entities.Alumno;
import com.taemoi.project.entities.AlumnoDeporte;
import com.taemoi.project.entities.Deporte;
import com.taemoi.project.entities.EstadoPreinscripcion;
import com.taemoi.project.entities.EstadoEmailCambioTurnos;
import com.taemoi.project.entities.EstadoEmailFinalizacion;
import com.taemoi.project.entities.Grupo;
import com.taemoi.project.entities.PlantillaPreinscripcion;
import com.taemoi.project.entities.Preinscripcion;
import com.taemoi.project.entities.RolFamiliar;
import com.taemoi.project.entities.TipoTarifa;
import com.taemoi.project.entities.Turno;
import com.taemoi.project.repositories.AlumnoDeporteRepository;
import com.taemoi.project.repositories.AlumnoRepository;
import com.taemoi.project.repositories.GradoRepository;
import com.taemoi.project.repositories.GrupoRepository;
import com.taemoi.project.repositories.PlantillaPreinscripcionRepository;
import com.taemoi.project.repositories.PreinscripcionRepository;
import com.taemoi.project.repositories.TurnoRepository;
import com.taemoi.project.events.PreinscripcionFinalizadaEvent;
import com.taemoi.project.events.PreinscripcionTurnosModificadosEvent;
import com.taemoi.project.exceptions.preinscripcion.PreinscripcionDuplicadaException;

@Service
public class PreinscripcionService {
 private static final Logger log=LoggerFactory.getLogger(PreinscripcionService.class);
 private static final Set<EstadoPreinscripcion> ESTADOS_NO_REPETIBLES=Set.of(EstadoPreinscripcion.PENDIENTE,EstadoPreinscripcion.EN_LISTA_ESPERA,EstadoPreinscripcion.FINALIZADA);
 private static final String MENSAJE_DUPLICADA="Ya existe una preinscripción para esta persona y deporte en la temporada actual.";
 private final PreinscripcionRepository repo; private final PlantillaPreinscripcionRepository plantillas; private final GrupoRepository grupos; private final TurnoRepository turnos;
 private final AlumnoRepository alumnos; private final AlumnoDeporteRepository alumnoDeportes; private final GradoRepository grados; private final TemporadaService temporadas; private final PDFService pdf;
 private final EmailService email; private final ConfiguracionSistemaService configuracion; private final ObjectMapper json; private final AforoPreinscripcionService aforo; private final ApplicationEventPublisher eventos;
 @Value("${app.preinscripciones.admin-email:}") private String adminEmail;
 @Value("${app.frontend.base-url:http://localhost:4200}") private String frontendBaseUrl;
 public PreinscripcionService(PreinscripcionRepository r,PlantillaPreinscripcionRepository p,GrupoRepository g,TurnoRepository t,AlumnoRepository a,AlumnoDeporteRepository ad,GradoRepository gr,TemporadaService ts,PDFService ps,EmailService es,ConfiguracionSistemaService cs,ObjectMapper om,AforoPreinscripcionService af,ApplicationEventPublisher ev){repo=r;plantillas=p;grupos=g;turnos=t;alumnos=a;alumnoDeportes=ad;grados=gr;temporadas=ts;pdf=ps;email=es;configuracion=cs;json=om;aforo=af;eventos=ev;}

 @Transactional public Map<String,Object> crear(PreinscripcionRequest d){return crear(d,null);}
 @Transactional public Map<String,Object> crear(PreinscripcionRequest d,String idempotencyKey){
  String idempotencyKeyHash=hashIdempotencia(idempotencyKey);
  if(idempotencyKeyHash!=null&&repo.existsByIdempotencyKeyHash(idempotencyKeyHash))throw duplicada();
  String dni=blank(d.dni())?null:d.dni().trim().toUpperCase(Locale.ROOT), temporada=temporadas.actual();String identidadHash=hash(identidadCanonica(dni,d.tutorDni(),d.nombre(),d.apellidos(),d.fechaNacimiento()));
  if(repo.existsByIdentidadHashAndDeporteAndTemporadaAndEstadoIn(identidadHash,d.deporte(),temporada,ESTADOS_NO_REPETIBLES))throw duplicada();
  List<Turno> horarios=aforo.bloquearTurnos(d.turnoIds());validarSeleccion(d.deporte(),d.fechaNacimiento(),temporada,horarios);
  Grupo grupo=horarios.get(0).getGrupo();
  if(Period.between(d.fechaNacimiento(),LocalDate.now()).getYears()<18&&(blank(d.tutorNombre())||blank(d.tutorDni()))) throw new IllegalArgumentException("Los menores deben indicar responsable legal y su DNI.");
  byte[] firma=decodificarFirma(d.firmaBase64()); PlantillaPreinscripcion plantilla=plantillas.findFirstByDeporteAndActivaTrueOrderByVersionDesc(d.deporte()).orElseThrow(()->new IllegalStateException("No hay plantilla activa."));
  Preinscripcion p=new Preinscripcion(); p.setReferencia(referencia()); p.setTemporada(temporada); p.setDeporte(d.deporte()); p.setEstado(aforo.algunaPlaza(horarios,temporada)?EstadoPreinscripcion.PENDIENTE:EstadoPreinscripcion.EN_LISTA_ESPERA); p.setNombre(clean(d.nombre())); p.setApellidos(clean(d.apellidos())); p.setDni(dni);p.setIdentidadHash(identidadHash); p.setFechaNacimiento(d.fechaNacimiento()); p.setDireccion(clean(d.direccion())); p.setTelefono(clean(d.telefono()));p.setTelefono2(blank(d.telefono2())?null:clean(d.telefono2())); p.setEmail(d.email().trim().toLowerCase(Locale.ROOT));p.setObservaciones(limpiarObservacion(d.observaciones()));p.setTieneDiscapacidad(d.tieneDiscapacidad()); p.setTutorNombre(clean(d.tutorNombre())); p.setTutorDni(blank(d.tutorDni())?null:d.tutorDni().trim().toUpperCase(Locale.ROOT)); p.setConsentimientoFotografico(d.consentimientoFotografico()); p.setAceptacionNormas(true); p.setFirmanteNombre(clean(d.firmanteNombre())); p.setFirma(firma); p.setGrupo(grupo);p.setTurnos(new LinkedHashSet<>(horarios)); p.setGrupoSnapshot(snapshotTurnos(d.deporte(),horarios)); p.setPlantilla(plantilla);
  try{p.setPlantillaSnapshot(json.writeValueAsString(Map.of("version",plantilla.getVersion(),"contenido",plantilla.getContenido(),"instrucciones",plantilla.getInstrucciones())));}catch(Exception e){throw new IllegalStateException(e);}
  String token=UUID.randomUUID().toString().replace("-",""); p.setTokenDocumentoHash(hash(token));p.setIdempotencyKeyHash(idempotencyKeyHash);p.setPdfFirmado(pdf.generarPreinscripcionFirmada(p));try{repo.saveAndFlush(p);}catch(DataIntegrityViolationException e){if(esConflictoDuplicado(e))throw duplicada(e);throw e;} enviarInicial(p); notificarAdmin(p);
  long posicion=p.getEstado()==EstadoPreinscripcion.EN_LISTA_ESPERA?aforo.posicion(p):0;Map<String,Object> respuesta=new LinkedHashMap<>();respuesta.put("referencia",p.getReferencia());respuesta.put("temporada",p.getTemporada());respuesta.put("tokenDocumento",token);respuesta.put("emailEnviado",p.getEmailEnviado());respuesta.put("estado",p.getEstado());respuesta.put("plazaAsignada",p.getEstado()==EstadoPreinscripcion.PENDIENTE);respuesta.put("posicionListaEspera",posicion==0?null:posicion);respuesta.put("mensaje",p.getEstado()==EstadoPreinscripcion.PENDIENTE?"Preinscripción recibida con plaza asignada.":"Preinscripción añadida a la lista de espera.");return respuesta;
 }
 public Map<String,Object> configuracion(Deporte deporte){PlantillaPreinscripcion p=plantillas.findFirstByDeporteAndActivaTrueOrderByVersionDesc(deporte).orElseThrow(); return Map.of("deporte",deporte,"version",p.getVersion(),"contenido",parse(p.getContenido()),"instrucciones",p.getInstrucciones());}
 public List<Map<String,Object>> grupos(Deporte deporte){String temporada=temporadas.actual();return grupos.findAll().stream().filter(g->g.getDeporte()==deporte).filter(this::visibleEnPreinscripcion).sorted(comparadorGrupos()).map(g->Map.<String,Object>of("id",g.getId(),"deporte",deporte,"nombre",nombrePublico(g),"rangoEdadMin",Optional.ofNullable(g.getRangoEdadMin()).orElse(0),"rangoEdadMax",Optional.ofNullable(g.getRangoEdadMax()).orElse(99),"turnos",turnos.findByGrupo(g).stream().sorted(comparadorTurnos()).map(t->turnoPublico(t,temporada)).toList(),"completo",aforo.completo(g,temporada))).toList();}
 public List<Map<String,Object>> turnos(Deporte deporte){String temporada=temporadas.actual();return turnos.findAllWithAlumnos().stream().filter(t->t.getGrupo()!=null&&t.getGrupo().getDeporte()==deporte&&visibleEnPreinscripcion(t.getGrupo())).map(t->{Map<String,Object> m=new LinkedHashMap<>();m.put("id",t.getId());m.put("deporte",deporte);m.put("grupo",t.getGrupo().getNombre());m.put("grupoId",t.getGrupo().getId());m.put("rangoEdadMin",Optional.ofNullable(t.getGrupo().getRangoEdadMin()).orElse(0));m.put("rangoEdadMax",Optional.ofNullable(t.getGrupo().getRangoEdadMax()).orElse(99));m.put("diaSemana",t.getDiaSemana());m.put("horaInicio",t.getHoraInicio());m.put("horaFin",t.getHoraFin());m.put("completo",aforo.completo(t,temporada));return m;}).toList();}
 public byte[] documento(String referencia,String token){Preinscripcion p=buscar(referencia); if(!MessageDigest.isEqual(hash(token).getBytes(),p.getTokenDocumentoHash().getBytes()))throw new SecurityException("Token de documento inválido."); return p.getPdfFirmado();}
public Page<Preinscripcion> listar(String temporada,Deporte deporte,EstadoPreinscripcion estado,String query,Pageable pageable){Specification<Preinscripcion> spec=Specification.unrestricted();if(temporada!=null&&!temporada.isBlank())spec=spec.and((root,q,cb)->cb.equal(root.get("temporada"),temporada));if(deporte!=null)spec=spec.and((root,q,cb)->cb.equal(root.get("deporte"),deporte));if(estado!=null)spec=spec.and((root,q,cb)->cb.equal(root.get("estado"),estado));if(query!=null&&!query.isBlank()){String patron="%"+query.trim().toUpperCase(Locale.ROOT)+"%";spec=spec.and((root,q,cb)->cb.or(cb.like(cb.upper(root.get("dni")),patron),cb.like(cb.upper(root.get("referencia")),patron),cb.like(cb.upper(root.get("nombre")),patron),cb.like(cb.upper(root.get("apellidos")),patron)));}return repo.findAll(spec,pageable);} public Preinscripcion buscar(String ref){return repo.findByReferencia(ref).orElseThrow(()->new NoSuchElementException("Preinscripción no encontrada."));}
 public List<Map<String,Object>> alumnosCoincidentes(Preinscripcion p){return buscarCandidatos(p).stream().map(a->candidatoDto(a,p.getDeporte())).toList();}
 private Map<String,Object> candidatoDto(Alumno a,Deporte deporte){Map<String,Object> m=new LinkedHashMap<>();m.put("id",a.getId());m.put("nombre",a.getNombre());m.put("apellidos",a.getApellidos());m.put("nif",a.getNif());m.put("fechaNacimiento",a.getFechaNacimiento());m.put("direccion",a.getDireccion());m.put("telefono",a.getTelefono());m.put("telefono2",a.getTelefono2());m.put("email",a.getEmail());m.put("tieneDiscapacidad",a.getTieneDiscapacidad());m.put("responsableLegalNombre",a.getResponsableLegalNombre());m.put("responsableLegalNif",a.getResponsableLegalNif());m.put("activo",Boolean.TRUE.equals(a.getActivo()));AlumnoDeporte ad=alumnoDeportes.findByAlumnoIdAndDeporte(a.getId(),deporte).orElse(null);m.put("deporteRegistrado",ad!=null);m.put("deporteActivo",ad!=null&&Boolean.TRUE.equals(ad.getActivo()));m.put("requiereDatosDeporte",ad==null);m.put("tipoTarifa",ad==null?null:ad.getTipoTarifa());m.put("cuantiaTarifa",ad==null?null:ad.getCuantiaTarifa());m.put("rolFamiliar",ad==null?null:ad.getRolFamiliar());m.put("grupoFamiliar",ad==null?null:ad.getGrupoFamiliar());return m;}
 private List<Alumno> buscarCandidatos(Preinscripcion p){if(!blank(p.getDni())){Optional<Alumno> exacto=alumnos.findByNif(p.getDni());if(exacto.isPresent())return List.of(exacto.get());}Date fecha=java.sql.Date.valueOf(p.getFechaNacimiento());return alumnos.findByFechaNacimiento(fecha).stream().filter(a->coincideIdentidadPersonal(a,p)).filter(a->blank(p.getDni())||blank(a.getNif())||p.getDni().equalsIgnoreCase(a.getNif())).toList();}
 public Long posicionListaEspera(Preinscripcion p){return p.getEstado()==EstadoPreinscripcion.EN_LISTA_ESPERA?aforo.posicion(p):null;}
 public List<Map<String,Object>> turnosSolicitados(Preinscripcion p){return turnosDe(p).stream().map(t->{Grupo g=t.getGrupo();Map<String,Object> m=new LinkedHashMap<>();m.put("id",t.getId());m.put("grupoId",g==null?null:g.getId());m.put("grupo",g==null?"Grupo no disponible":g.getNombre());m.put("diaSemana",t.getDiaSemana());m.put("horaInicio",t.getHoraInicio());m.put("horaFin",t.getHoraFin());return m;}).toList();}
 public String grupoOriginal(Preinscripcion p){return p.getGrupoSnapshot()!=null?p.getGrupoSnapshot():p.getTurnoSnapshot();}
 public String grupoVigente(Preinscripcion p){return snapshotTurnos(p.getDeporte(),turnosDe(p));}
 @Transactional public void cancelar(String ref){Preinscripcion p=buscar(ref);if(p.getEstado()!=EstadoPreinscripcion.PENDIENTE&&p.getEstado()!=EstadoPreinscripcion.EN_LISTA_ESPERA)throw new IllegalStateException("Solo se puede cancelar una solicitud pendiente o en lista de espera.");boolean libera=p.getEstado()==EstadoPreinscripcion.PENDIENTE;String temporada=p.getTemporada();List<Turno> seleccion=turnosDe(p);aforo.bloquearTurnos(seleccion.stream().map(Turno::getId).toList());p.setEstado(EstadoPreinscripcion.CANCELADA);p.setCanceladaEn(Instant.now());repo.saveAndFlush(p);if(libera)promocionarDisponibles(temporada);}
 @Transactional public void eliminar(String ref){Preinscripcion p=buscar(ref);if(p.getEstado()!=EstadoPreinscripcion.CANCELADA)throw new IllegalStateException("Solo se pueden eliminar definitivamente las solicitudes canceladas.");repo.delete(p);}
 @Transactional public void reenviar(String ref){reenviarSolicitudOriginal(buscar(ref));}
 @Transactional public void reenviarCambioTurnos(String ref){Preinscripcion p=repo.findByReferenciaForUpdate(ref).orElseThrow(()->new NoSuchElementException("Preinscripción no encontrada."));if(p.getEstado()!=EstadoPreinscripcion.PENDIENTE)throw new IllegalStateException("El aviso de cambio solo puede reenviarse mientras la solicitud siga pendiente.");if(blank(p.getEmailCambioTurnosAnteriorSnapshot())||blank(p.getEmailCambioTurnosNuevoSnapshot()))throw new IllegalStateException("La solicitud no tiene ningún cambio de turnos para reenviar.");p.setEstadoEmailCambioTurnos(EstadoEmailCambioTurnos.PENDIENTE);p.setEmailCambioTurnosUltimoError(null);eventos.publishEvent(new PreinscripcionTurnosModificadosEvent(p.getReferencia()));}
 @Transactional public void reenviarFinalizacion(String ref){Preinscripcion p=repo.findByReferenciaForUpdate(ref).orElseThrow(()->new NoSuchElementException("Preinscripción no encontrada."));if(p.getEstado()!=EstadoPreinscripcion.FINALIZADA)throw new IllegalStateException("La confirmación final solo puede reenviarse para preinscripciones finalizadas.");p.setEstadoEmailFinalizacion(EstadoEmailFinalizacion.PENDIENTE);p.setEmailFinalizacionUltimoError(null);eventos.publishEvent(new PreinscripcionFinalizadaEvent(p.getReferencia()));}
 @Transactional public void finalizar(String ref,FinalizarPreinscripcionRequest d){
  Preinscripcion p=repo.findByReferenciaForUpdate(ref).orElseThrow(()->new NoSuchElementException("Preinscripción no encontrada."));
  if(p.getEstado()!=EstadoPreinscripcion.PENDIENTE)throw new IllegalStateException("Solo puede finalizarse una preinscripción con plaza asignada.");
  List<Turno> horarios=turnosDe(p);horarios=aforo.bloquearTurnos(horarios.stream().map(Turno::getId).toList());validarSeleccionAdministrativa(p.getDeporte(),horarios);
  Boolean discapacidad=p.getTieneDiscapacidad()!=null?p.getTieneDiscapacidad():d.discapacidadHistorica();if(discapacidad==null)throw new IllegalArgumentException("Debe confirmarse si el alumno tiene discapacidad.");Alumno a;
  if(d.accionAlumno()==FinalizarPreinscripcionRequest.AccionAlumno.VINCULAR_EXISTENTE){if(d.alumnoId()==null)throw new IllegalArgumentException("Debe seleccionarse una ficha existente.");a=alumnos.findById(d.alumnoId()).orElseThrow(()->new IllegalArgumentException("Alumno no encontrado."));if(!esCandidatoValido(a,p))throw new IllegalArgumentException("La ficha seleccionada no coincide con la identidad de la preinscripción.");if(!blank(p.getDni())){Optional<Alumno> porDni=alumnos.findByNif(p.getDni());if(porDni.isPresent()&&!porDni.get().getId().equals(a.getId()))throw new IllegalArgumentException("El DNI/NIE ya pertenece a otro alumno.");}validarYAplicarDecisionEmail(a,p,d.decisionEmail());aplicarCamposConfirmados(a,p,discapacidad,d.camposActualizarSeguros());}
  else if(d.accionAlumno()==FinalizarPreinscripcionRequest.AccionAlumno.CREAR_NUEVO){if(!blank(p.getDni())&&alumnos.findByNif(p.getDni()).isPresent())throw new IllegalArgumentException("Ya existe una ficha con el DNI/NIE de la preinscripción.");a=crearAlumnoDesdePreinscripcion(p,discapacidad);}
  else throw new IllegalArgumentException("Debe indicarse si se crea o se vincula la ficha del alumno.");
  a.setAutorizacionWeb(Boolean.TRUE.equals(p.getConsentimientoFotografico()));reactivarAlumno(a);alumnos.saveAndFlush(a);asegurarDeporte(a,p.getDeporte(),d.datosDeporte());
  sincronizarAsignaciones(a,p.getDeporte(),horarios);alumnos.save(a);
  p.setAlumno(a);p.setEstado(EstadoPreinscripcion.FINALIZADA);p.setFinalizadaEn(Instant.now());p.setEstadoEmailFinalizacion(EstadoEmailFinalizacion.PENDIENTE);p.setEmailFinalizacionUltimoError(null);eventos.publishEvent(new PreinscripcionFinalizadaEvent(p.getReferencia()));
 }
 @Transactional public void actualizarTurnos(String ref,ActualizarTurnosPreinscripcionRequest d){
  Preinscripcion p=repo.findByReferenciaForUpdate(ref).orElseThrow(()->new NoSuchElementException("Preinscripción no encontrada."));
  if(p.getEstado()!=EstadoPreinscripcion.PENDIENTE&&p.getEstado()!=EstadoPreinscripcion.EN_LISTA_ESPERA)throw new IllegalStateException("Solo pueden modificarse los turnos de una solicitud pendiente o en lista de espera.");
  List<Turno> anteriores=turnosDe(p);Set<Long> idsBloqueo=new java.util.TreeSet<>();anteriores.forEach(t->idsBloqueo.add(t.getId()));idsBloqueo.addAll(d.turnoIds());
  Map<Long,Turno> bloqueados=aforo.bloquearTurnos(idsBloqueo).stream().collect(java.util.stream.Collectors.toMap(Turno::getId,t->t));
  List<Turno> nuevos=d.turnoIds().stream().map(bloqueados::get).sorted(comparadorTurnos()).toList();validarSeleccionAdministrativa(p.getDeporte(),nuevos);
  Set<Long> idsAnteriores=anteriores.stream().map(Turno::getId).collect(java.util.stream.Collectors.toSet());Set<Long> idsNuevos=nuevos.stream().map(Turno::getId).collect(java.util.stream.Collectors.toSet());if(idsAnteriores.equals(idsNuevos))return;
  boolean liberaPlaza=p.getEstado()==EstadoPreinscripcion.PENDIENTE;String snapshotAnterior=snapshotTurnos(p.getDeporte(),anteriores),snapshotNuevo=snapshotTurnos(p.getDeporte(),nuevos);
  p.setTurno(null);p.setGrupo(nuevos.get(0).getGrupo());p.setTurnos(new LinkedHashSet<>(nuevos));p.setEstado(EstadoPreinscripcion.PENDIENTE);p.setEstadoEmailCambioTurnos(EstadoEmailCambioTurnos.PENDIENTE);p.setEmailCambioTurnosEnviadoEn(null);p.setEmailCambioTurnosUltimoError(null);p.setTurnosModificadosEn(Instant.now());p.setEmailCambioTurnosAnteriorSnapshot(snapshotAnterior);p.setEmailCambioTurnosNuevoSnapshot(snapshotNuevo);repo.saveAndFlush(p);eventos.publishEvent(new PreinscripcionTurnosModificadosEvent(p.getReferencia()));if(liberaPlaza)promocionarDisponibles(p.getTemporada());
 }
 private Alumno crearAlumnoDesdePreinscripcion(Preinscripcion p,Boolean discapacidad){Date hoy=new Date();Alumno a=new Alumno();a.setNombre(mayusculas(p.getNombre()));a.setApellidos(mayusculas(p.getApellidos()));a.setFechaNacimiento(java.sql.Date.valueOf(p.getFechaNacimiento()));a.setNif(p.getDni());a.setDireccion(p.getDireccion());a.setTelefono(normalizarTelefono(p.getTelefono()));a.setTelefono2(normalizarTelefonoOpcional(p.getTelefono2()));a.setEmail(p.getEmail());a.setResponsableLegalNombre(p.getTutorNombre());a.setResponsableLegalNif(p.getTutorDni());a.setNumeroExpediente(Optional.ofNullable(alumnos.findMaxNumeroExpediente()).orElse(0)+1);a.setFechaAlta(hoy);a.setFechaAltaInicial(hoy);a.setActivo(true);a.setFechaBaja(null);a.setTieneDiscapacidad(discapacidad);return alumnos.saveAndFlush(a);}
 private void aplicarCamposConfirmados(Alumno a,Preinscripcion p,Boolean discapacidad,Set<FinalizarPreinscripcionRequest.CampoActualizable> campos){if(campos.contains(FinalizarPreinscripcionRequest.CampoActualizable.NOMBRE))a.setNombre(p.getNombre());if(campos.contains(FinalizarPreinscripcionRequest.CampoActualizable.APELLIDOS))a.setApellidos(p.getApellidos());if(campos.contains(FinalizarPreinscripcionRequest.CampoActualizable.FECHA_NACIMIENTO))a.setFechaNacimiento(java.sql.Date.valueOf(p.getFechaNacimiento()));if(campos.contains(FinalizarPreinscripcionRequest.CampoActualizable.DIRECCION))a.setDireccion(p.getDireccion());if(campos.contains(FinalizarPreinscripcionRequest.CampoActualizable.TELEFONO))a.setTelefono(normalizarTelefono(p.getTelefono()));if(campos.contains(FinalizarPreinscripcionRequest.CampoActualizable.TELEFONO2)&&!blank(p.getTelefono2()))a.setTelefono2(normalizarTelefonoOpcional(p.getTelefono2()));if(campos.contains(FinalizarPreinscripcionRequest.CampoActualizable.NIF)&&!blank(p.getDni()))a.setNif(p.getDni());if(campos.contains(FinalizarPreinscripcionRequest.CampoActualizable.TIENE_DISCAPACIDAD))a.setTieneDiscapacidad(discapacidad);if(campos.contains(FinalizarPreinscripcionRequest.CampoActualizable.RESPONSABLE_LEGAL_NOMBRE)&&esMenor(p))a.setResponsableLegalNombre(p.getTutorNombre());if(campos.contains(FinalizarPreinscripcionRequest.CampoActualizable.RESPONSABLE_LEGAL_NIF)&&esMenor(p))a.setResponsableLegalNif(p.getTutorDni());}
 private void validarYAplicarDecisionEmail(Alumno a,Preinscripcion p,FinalizarPreinscripcionRequest.DecisionEmail decision){String ficha=normalizarEmail(a.getEmail()),solicitud=normalizarEmail(p.getEmail());if(ficha.equals(solicitud)){if(blank(a.getEmail()))a.setEmail(p.getEmail());return;}if(decision==null)throw new IllegalArgumentException("Los correos de la ficha y la preinscripción son diferentes. Debe elegirse expresamente cuál conservar.");if(decision==FinalizarPreinscripcionRequest.DecisionEmail.USAR_PREINSCRIPCION)a.setEmail(p.getEmail());if(blank(a.getEmail()))throw new IllegalArgumentException("La ficha debe conservar un correo electrónico para acceder al portal.");}
 private String normalizarEmail(String value){return blank(value)?"":value.trim().toLowerCase(Locale.ROOT);}
 private void reactivarAlumno(Alumno a){if(Boolean.TRUE.equals(a.getActivo()))return;Date hoy=new Date();a.setActivo(true);a.setFechaBaja(null);a.setFechaAlta(hoy);if(a.getFechaAltaInicial()==null)a.setFechaAltaInicial(hoy);}
 private void sincronizarAsignaciones(Alumno a,Deporte deporte,List<Turno> horarios){
  Map<Long,Turno> turnosSeleccionados=new LinkedHashMap<>();Map<Long,Grupo> gruposSeleccionados=new LinkedHashMap<>();for(Turno horario:horarios){turnosSeleccionados.putIfAbsent(horario.getId(),horario);Grupo grupo=horario.getGrupo();gruposSeleccionados.putIfAbsent(grupo.getId(),grupo);}
  new ArrayList<>(a.getTurnos()).stream().filter(t->t.getGrupo()!=null&&t.getGrupo().getDeporte()==deporte).filter(t->!turnosSeleccionados.containsKey(t.getId())).forEach(a::removeTurno);
  turnosSeleccionados.values().stream().filter(t->a.getTurnos().stream().noneMatch(actual->java.util.Objects.equals(actual.getId(),t.getId()))).forEach(a::addTurno);
  new ArrayList<>(a.getGrupos()).stream().filter(g->g.getDeporte()==deporte).filter(g->!gruposSeleccionados.containsKey(g.getId())).forEach(g->g.removeAlumno(a));
  gruposSeleccionados.values().stream().filter(g->a.getGrupos().stream().noneMatch(actual->java.util.Objects.equals(actual.getId(),g.getId()))).forEach(g->g.addAlumno(a));
 }
 private void asegurarDeporte(Alumno a,Deporte deporte,FinalizarPreinscripcionRequest.DatosAltaDeporte datos){Optional<AlumnoDeporte> existente=alumnoDeportes.findByAlumnoIdAndDeporte(a.getId(),deporte);boolean nuevo=existente.isEmpty();validarDatosDeporte(deporte,datos,nuevo);Date hoy=new Date();AlumnoDeporte ad=existente.orElseGet(AlumnoDeporte::new);if(nuevo){ad.setAlumno(a);ad.setDeporte(deporte);ad.setActivo(true);ad.setPrincipal(alumnoDeportes.countByAlumnoIdAndActivoTrue(a.getId())==0);ad.setFechaAlta(hoy);ad.setFechaAltaInicial(hoy);ad.setAptoParaExamen(false);ad.setCompetidor(false);ad.setTieneLicencia(false);}else if(!Boolean.TRUE.equals(ad.getActivo())){long activos=alumnoDeportes.countByAlumnoIdAndActivoTrue(a.getId());ad.setActivo(true);ad.setFechaBaja(null);ad.setFechaAlta(hoy);if(ad.getFechaAltaInicial()==null)ad.setFechaAltaInicial(hoy);if(activos==0)ad.setPrincipal(true);}ad.setTipoTarifa(datos.tipoTarifa());ad.setCuantiaTarifa(datos.cuantiaTarifa());ad.setRolFamiliar(datos.rolFamiliar());ad.setGrupoFamiliar(clean(datos.grupoFamiliar()));if(nuevo&&(deporte==Deporte.TAEKWONDO||deporte==Deporte.KICKBOXING)){var grado=grados.findByTipoGrado(datos.grado());if(grado==null)throw new IllegalArgumentException("Grado no encontrado.");ad.setGrado(grado);ad.setFechaGrado(java.sql.Date.valueOf(datos.fechaGrado()));}alumnoDeportes.save(ad);}
 private void validarDatosDeporte(Deporte deporte,FinalizarPreinscripcionRequest.DatosAltaDeporte datos,boolean altaNueva){if(datos==null||datos.tipoTarifa()==null||datos.cuantiaTarifa()==null)throw new IllegalArgumentException("Tipo y cuantía de tarifa son obligatorios para el alta deportiva.");boolean tarifaValida=switch(deporte){case TAEKWONDO->datos.tipoTarifa()!=TipoTarifa.KICKBOXING&&datos.tipoTarifa()!=TipoTarifa.PILATES&&datos.tipoTarifa()!=TipoTarifa.DEFENSA_PERSONAL_FEMENINA;case KICKBOXING->datos.tipoTarifa()==TipoTarifa.KICKBOXING;case PILATES->datos.tipoTarifa()==TipoTarifa.PILATES;case DEFENSA_PERSONAL_FEMENINA->datos.tipoTarifa()==TipoTarifa.DEFENSA_PERSONAL_FEMENINA;};if(!tarifaValida)throw new IllegalArgumentException("La tarifa no corresponde al deporte seleccionado.");if(datos.tipoTarifa()==TipoTarifa.PADRES_HIJOS&&(datos.rolFamiliar()==null||datos.rolFamiliar()==RolFamiliar.NINGUNO))throw new IllegalArgumentException("La tarifa padres/hijos requiere rol familiar.");if(datos.tipoTarifa()==TipoTarifa.HERMANOS&&blank(datos.grupoFamiliar()))throw new IllegalArgumentException("La tarifa hermanos requiere grupo familiar.");boolean requiereGrado=altaNueva&&(deporte==Deporte.TAEKWONDO||deporte==Deporte.KICKBOXING);if(requiereGrado&&(datos.grado()==null||datos.fechaGrado()==null))throw new IllegalArgumentException("Grado y fecha de grado son obligatorios para este deporte.");if(altaNueva&&deporte==Deporte.KICKBOXING&&!Set.of(com.taemoi.project.entities.TipoGrado.BLANCO,com.taemoi.project.entities.TipoGrado.AMARILLO,com.taemoi.project.entities.TipoGrado.NARANJA,com.taemoi.project.entities.TipoGrado.VERDE,com.taemoi.project.entities.TipoGrado.AZUL,com.taemoi.project.entities.TipoGrado.ROJO,com.taemoi.project.entities.TipoGrado.NEGRO_1_DAN,com.taemoi.project.entities.TipoGrado.NEGRO_2_DAN,com.taemoi.project.entities.TipoGrado.NEGRO_3_DAN,com.taemoi.project.entities.TipoGrado.NEGRO_4_DAN,com.taemoi.project.entities.TipoGrado.NEGRO_5_DAN).contains(datos.grado()))throw new IllegalArgumentException("El grado no es válido para Kickboxing.");}
 private Integer normalizarTelefono(String telefono){String digitos=telefono==null?"":telefono.replaceAll("\\D","");if(digitos.length()==13&&digitos.startsWith("0034"))digitos=digitos.substring(4);else if(digitos.length()==11&&digitos.startsWith("34"))digitos=digitos.substring(2);if(!digitos.matches("[6789]\\d{8}"))throw new IllegalArgumentException("El teléfono debe ser un número español de nueve dígitos, con prefijo +34 opcional.");return Integer.valueOf(digitos);}
 private Integer normalizarTelefonoOpcional(String telefono){return blank(telefono)?null:normalizarTelefono(telefono);}
 private String mayusculas(String valor){String limpio=clean(valor);return limpio==null?null:limpio.toUpperCase(Locale.ROOT);}
 public Map<String,Object> plantillas(Deporte deporte){List<PlantillaPreinscripcion> lista=plantillas.findByDeporteOrderByVersionDesc(deporte);PlantillaPreinscripcion activa=lista.stream().filter(x->Boolean.TRUE.equals(x.getActiva())).findFirst().orElseThrow(()->new NoSuchElementException("No hay plantilla activa."));return Map.of("activa",plantillaDto(activa),"historial",lista.stream().map(this::plantillaDto).toList());}
 @Transactional public Map<String,Object> nuevaPlantilla(Deporte deporte,PlantillaPreinscripcionRequest body){return plantillaDto(guardarPlantilla(deporte,body));}
 public byte[] preview(Deporte deporte,PlantillaPreinscripcionRequest body){String contenido=contenido(body);return pdf.generarPreviewPreinscripcion(deporte,contenido,limpiar(body.instrucciones(),3000));}
 @Transactional public Map<String,Object> restaurar(Deporte deporte,Integer version){PlantillaPreinscripcion origen=plantillas.findByDeporteAndVersion(deporte,version).orElseThrow(()->new NoSuchElementException("Versión no encontrada."));PlantillaPreinscripcionRequest body=leerPlantilla(origen);return plantillaDto(guardarPlantilla(deporte,body));}
 private PlantillaPreinscripcion guardarPlantilla(Deporte deporte,PlantillaPreinscripcionRequest body){String contenido=contenido(body);List<PlantillaPreinscripcion> anteriores=plantillas.findByDeporteOrderByVersionDesc(deporte);anteriores.forEach(x->x.setActiva(false));PlantillaPreinscripcion p=new PlantillaPreinscripcion();p.setDeporte(deporte);p.setVersion(anteriores.isEmpty()?1:anteriores.get(0).getVersion()+1);p.setActiva(true);p.setContenido(contenido);p.setInstrucciones(limpiar(body.instrucciones(),3000));return plantillas.save(p);}
 private String contenido(PlantillaPreinscripcionRequest b){try{return json.writeValueAsString(Map.of("cabecera",limpiar(b.cabecera(),120),"contacto",limpiar(b.contacto(),180),"titulo",limpiar(b.titulo(),180),"consentimiento",limpiar(b.consentimiento(),1500),"normas",b.normas().stream().map(x->limpiar(x,2000)).toList(),"importes",limpiar(b.importes(),3000)));}catch(Exception e){throw new IllegalArgumentException("Contenido de plantilla inválido.");}}
 private PlantillaPreinscripcionRequest leerPlantilla(PlantillaPreinscripcion p){try{var n=json.readTree(p.getContenido());List<String> normas=new java.util.ArrayList<>();n.path("normas").forEach(x->normas.add(x.asText()));return new PlantillaPreinscripcionRequest(n.path("cabecera").asText(),n.path("contacto").asText(),n.path("titulo").asText(),n.path("consentimiento").asText(),normas,n.path("importes").asText(),p.getInstrucciones());}catch(Exception e){throw new IllegalStateException("Plantilla histórica inválida.");}}
 private Map<String,Object> plantillaDto(PlantillaPreinscripcion p){Map<String,Object> m=new LinkedHashMap<>();m.put("id",p.getId());m.put("deporte",p.getDeporte());m.put("version",p.getVersion());m.put("activa",p.getActiva());m.put("creadaEn",p.getCreadaEn());m.put("contenido",parse(p.getContenido()));m.put("instrucciones",p.getInstrucciones());return m;}
 private String limpiar(String value,int max){String v=clean(value);if(v==null||v.isBlank())throw new IllegalArgumentException("Todos los campos y al menos una norma son obligatorios.");if(v.length()>max)throw new IllegalArgumentException("Contenido demasiado largo.");return v;}
 @Transactional public void promocionarGrupo(Long grupoId,String temporada){promocionarDisponibles(temporada);}
 @Transactional public void promocionarTodas(){promocionarDisponibles(temporadas.actual());}
 private void promocionarDisponibles(String temporada){for(Preinscripcion p:aforo.cola(temporada)){List<Turno> seleccion=turnosDe(p);seleccion=aforo.bloquearTurnos(seleccion.stream().map(Turno::getId).toList());if(!aforo.algunaPlaza(seleccion,temporada))continue;p.setEstado(EstadoPreinscripcion.PENDIENTE);p.setPromocionadaEn(Instant.now());repo.saveAndFlush(p);notificarPromocion(p);}}
 private void enviarInicial(Preinscripcion p){p.setEmailIntentos(p.getEmailIntentos()+1);try{email.sendEmailConAdjunto(p.getEmail(),asuntoCliente(p),htmlConfirmacion(p),"preinscripcion-"+p.getReferencia()+".pdf",p.getPdfFirmado());p.setEmailEnviado(true);p.setEmailUltimoError(null);}catch(Exception e){p.setEmailEnviado(false);p.setEmailUltimoError(clean(e.getMessage()));}}
 private void reenviarSolicitudOriginal(Preinscripcion p){p.setEmailIntentos(p.getEmailIntentos()+1);try{email.sendEmailConAdjunto(p.getEmail(),"Copia de la solicitud original · "+p.getReferencia(),htmlSolicitudOriginal(p),"solicitud-original-"+p.getReferencia()+".pdf",p.getPdfFirmado());p.setEmailEnviado(true);p.setEmailUltimoError(null);}catch(Exception e){p.setEmailEnviado(false);p.setEmailUltimoError(clean(e.getMessage()));}}
 private String asuntoCliente(Preinscripcion p){return p.getEstado()==EstadoPreinscripcion.EN_LISTA_ESPERA?"Lista de espera · "+p.getReferencia():"Plaza asignada · "+p.getReferencia();}
 private String htmlConfirmacion(Preinscripcion p){boolean espera=p.getEstado()==EstadoPreinscripcion.EN_LISTA_ESPERA;String estado=espera?"<p style='padding:12px;border-left:4px solid #b7791f;background:#fff8e6'><strong>Lista de espera.</strong> Tu posición actual es <strong>"+aforo.posicion(p)+"</strong>. Te avisaremos automáticamente cuando uno de los horarios tenga plaza.</p>":"<p style='padding:12px;border-left:4px solid #237a57;background:#edf8f3'><strong>Plaza asignada.</strong> Esta preinscripción ya cuenta en el aforo de todos los turnos elegidos.</p>";return "<div style='font-family:Arial,sans-serif;color:#172126;line-height:1.55;max-width:640px'><h2>Hemos recibido tu preinscripción</h2><p>Hola, "+esc(p.getNombre())+".</p><p>Solicitud para <strong>"+esc(nombreDeporte(p.getDeporte()))+"</strong>, temporada <strong>"+esc(p.getTemporada())+"</strong>, referencia <strong>"+esc(p.getReferencia())+"</strong>.</p>"+estado+"<p><strong>Horarios:</strong> "+esc(p.getGrupoSnapshot())+"</p>"+bloqueObservaciones(p)+"<h3>Próximos pasos</h3><p>"+esc(p.getPlantilla().getInstrucciones())+"</p><p>Conserva este correo y la referencia.</p><p>Un saludo,<br/><strong>Moi's Kim Do</strong></p></div>";}
 private String htmlSolicitudOriginal(Preinscripcion p){return "<div style='font-family:Arial,sans-serif;color:#172126;line-height:1.55;max-width:640px'><h2>Copia de tu solicitud original</h2><p>Hola, "+esc(p.getNombre())+".</p><p>Te reenviamos la solicitud original firmada para <strong>"+esc(nombreDeporte(p.getDeporte()))+"</strong>, temporada <strong>"+esc(p.getTemporada())+"</strong>, referencia <strong>"+esc(p.getReferencia())+"</strong>.</p><p><strong>Horario solicitado originalmente:</strong> "+esc(grupoOriginal(p))+"</p>"+bloqueObservaciones(p)+"<p>Este correo y el PDF adjunto reflejan los datos presentados originalmente y no informan sobre el estado o la asignación vigente.</p><p>Un saludo,<br/><strong>Moi's Kim Do</strong></p></div>";}
 private void notificarAdmin(Preinscripcion p){if(adminEmail==null||adminEmail.isBlank())return;try{email.sendEmail(adminEmail.trim(),"Nueva preinscripción recibida: "+p.getReferencia(),htmlAdmin(p));}catch(Exception e){log.warn("No se pudo enviar aviso interno de preinscripción {}: {}",p.getReferencia(),e.getMessage());}}
 private String htmlAdmin(Preinscripcion p){String url=frontendBaseUrl.replaceAll("/+$","")+"/preinscripciones";String estado=p.getEstado()==EstadoPreinscripcion.EN_LISTA_ESPERA?"Lista de espera · posición "+aforo.posicion(p):"Plaza asignada";String telefonos=p.getTelefono()+(blank(p.getTelefono2())?"":" · "+p.getTelefono2());return "<h2>Nueva preinscripción recibida</h2><p><strong>Referencia:</strong> "+esc(p.getReferencia())+"</p><table cellpadding='6' cellspacing='0' border='1' style='border-collapse:collapse'><tr><td><strong>Alumno/a</strong></td><td>"+esc(p.getNombre()+" "+p.getApellidos())+"</td></tr><tr><td><strong>DNI/NIE</strong></td><td>"+esc(blank(p.getDni())?"No facilitado":p.getDni())+"</td></tr><tr><td><strong>Deporte / grupo</strong></td><td>"+esc(p.getGrupoSnapshot())+"</td></tr><tr><td><strong>Estado</strong></td><td>"+esc(estado)+"</td></tr><tr><td><strong>Teléfonos</strong></td><td>"+esc(telefonos)+"</td></tr><tr><td><strong>Discapacidad</strong></td><td>"+(Boolean.TRUE.equals(p.getTieneDiscapacidad())?"Sí":"No")+"</td></tr><tr><td><strong>Email</strong></td><td>"+esc(p.getEmail())+"</td></tr><tr><td><strong>Temporada</strong></td><td>"+esc(p.getTemporada())+"</td></tr><tr><td><strong>Observaciones</strong></td><td>"+esc(blank(p.getObservaciones())?"Sin observaciones":p.getObservaciones())+"</td></tr></table><p>Revisar en el panel: <a href='"+esc(url)+"'>"+esc(url)+"</a></p>";}
 private String bloqueObservaciones(Preinscripcion p){return blank(p.getObservaciones())?"":"<h3>Tu observación</h3><p style='padding:12px;background:#f4f6f6;border-left:4px solid #547078;white-space:pre-wrap'>"+esc(p.getObservaciones())+"</p><p>Nuestro equipo la revisará y se pondrá en contacto contigo si es necesario.</p>";}
 private void notificarPromocion(Preinscripcion p){try{email.sendEmail(p.getEmail(),"Ya tienes plaza · "+p.getReferencia(),"<h2>Tu preinscripción ya tiene plaza</h2><p>Se ha liberado una plaza para <strong>"+esc(nombreDeporte(p.getDeporte()))+"</strong>. Tu preinscripción "+esc(p.getReferencia())+" ya cuenta en el aforo.</p><p>"+esc(p.getPlantilla().getInstrucciones())+"</p>");}catch(Exception e){log.warn("No se pudo avisar de promoción {}: {}",p.getReferencia(),e.getMessage());}if(adminEmail==null||adminEmail.isBlank())return;try{email.sendEmail(adminEmail.trim(),"Lista de espera promocionada: "+p.getReferencia(),"<h2>Plaza asignada automáticamente</h2><p>"+esc(p.getNombre()+" "+p.getApellidos())+" · "+esc(nombreDeporte(p.getDeporte()))+" · "+esc(p.getReferencia())+".</p>");}catch(Exception e){log.warn("No se pudo avisar al admin de promoción {}: {}",p.getReferencia(),e.getMessage());}}
 private byte[] decodificarFirma(String value){try{String b=value.substring(value.indexOf(',')+1);byte[] data=java.util.Base64.getDecoder().decode(b);if(data.length<100||data.length>500000)throw new IllegalArgumentException();BufferedImage original=ImageIO.read(new ByteArrayInputStream(data));if(original==null||original.getWidth()>2400||original.getHeight()>1200)throw new IllegalArgumentException();BufferedImage limpia=new BufferedImage(original.getWidth(),original.getHeight(),BufferedImage.TYPE_INT_RGB);Graphics2D g=limpia.createGraphics();g.setColor(Color.WHITE);g.fillRect(0,0,limpia.getWidth(),limpia.getHeight());g.drawImage(original,0,0,null);g.dispose();ByteArrayOutputStream out=new ByteArrayOutputStream();ImageIO.write(limpia,"png",out);return out.toByteArray();}catch(Exception e){throw new IllegalArgumentException("La firma no es una imagen válida o excede 500 KB.");}}
 private Map<String,Object> turnoPublico(Turno t,String temporada){return Map.of("id",t.getId(),"diaSemana",t.getDiaSemana(),"horaInicio",t.getHoraInicio(),"horaFin",t.getHoraFin(),"completo",aforo.completo(t,temporada));}
 private boolean visibleEnPreinscripcion(Grupo g){return g.getDeporte()!=Deporte.TAEKWONDO||!normalizar(g.getNombre()+" "+g.getTipo()).contains("competicion");}
 private String nombrePublico(Grupo g){return nombreDeporte(g.getDeporte());}
 private String nombreDeporte(Deporte deporte){return switch(deporte){case TAEKWONDO -> "Taekwondo";case KICKBOXING -> "Kickboxing";case PILATES -> "Pilates";case DEFENSA_PERSONAL_FEMENINA -> "Defensa personal femenina";};}
 private String normalizar(String s){return s==null?"":java.text.Normalizer.normalize(s,java.text.Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ROOT);}
 private String normalizarIdentidad(String s){return normalizar(clean(s)).replaceAll("[^a-z0-9]","");}
 private String identidadCanonica(String dni,String tutorDni,String nombre,String apellidos,LocalDate nacimiento){if(!blank(dni))return "DNI|"+dni.trim().toUpperCase(Locale.ROOT);return "MENOR|"+(blank(tutorDni)?"":tutorDni.trim().toUpperCase(Locale.ROOT))+"|"+normalizarIdentidad(nombre)+"|"+normalizarIdentidad(apellidos)+"|"+nacimiento;}
 private boolean coincideIdentidadPersonal(Alumno a,Preinscripcion p){if(a.getFechaNacimiento()==null)return false;LocalDate nacimiento=new java.sql.Date(a.getFechaNacimiento().getTime()).toLocalDate();return nacimiento.equals(p.getFechaNacimiento())&&normalizarIdentidad(a.getNombre()).equals(normalizarIdentidad(p.getNombre()))&&normalizarIdentidad(a.getApellidos()).equals(normalizarIdentidad(p.getApellidos()));}
 private boolean esCandidatoValido(Alumno a,Preinscripcion p){if(!blank(p.getDni())&&!blank(a.getNif())&&p.getDni().equalsIgnoreCase(a.getNif()))return true;if(!blank(p.getDni())&&!blank(a.getNif()))return false;return coincideIdentidadPersonal(a,p);}
 private boolean esMenor(Preinscripcion p){return Period.between(p.getFechaNacimiento(),LocalDate.now()).getYears()<18;}
 private List<Turno> turnosDe(Preinscripcion p){if(p.getTurnos()!=null&&!p.getTurnos().isEmpty())return p.getTurnos().stream().sorted(comparadorTurnos()).toList();if(p.getTurno()!=null)return List.of(p.getTurno());if(p.getGrupo()!=null){List<Turno> legacy=turnos.findByGrupo(p.getGrupo()).stream().sorted(comparadorTurnos()).toList();if(!legacy.isEmpty())return legacy;}throw new IllegalStateException("La solicitud no tiene turnos asociados.");}
 void validarSeleccion(Deporte deporte,LocalDate nacimiento,String temporada,List<Turno> seleccion){validarSeleccionAdministrativa(deporte,seleccion);int edad=temporadas.edadCohorte(nacimiento,temporada);for(Turno t:seleccion){Grupo g=t.getGrupo();int minima=Optional.ofNullable(g.getRangoEdadMin()).orElse(0),maxima=Optional.ofNullable(g.getRangoEdadMax()).orElse(99);if(edad<minima||edad>maxima)throw new IllegalArgumentException("Uno de los turnos no es compatible con la edad de cohorte para la temporada indicada.");}}
 private void validarSeleccionAdministrativa(Deporte deporte,List<Turno> seleccion){if(seleccion==null||seleccion.isEmpty())throw new IllegalArgumentException("Es necesario seleccionar al menos un turno.");Set<String> dias=new java.util.HashSet<>();for(Turno t:seleccion){Grupo g=t.getGrupo();if(g==null||g.getDeporte()!=deporte)throw new IllegalArgumentException("Todos los turnos deben pertenecer al deporte seleccionado.");if(!visibleEnPreinscripcion(g))throw new IllegalArgumentException("Uno de los turnos no está disponible para preinscripción.");if(!dias.add(normalizar(t.getDiaSemana())))throw new IllegalArgumentException("Solo se puede seleccionar un turno por día.");}}
 private String snapshotTurnos(Deporte deporte,List<Turno> horarios){String hs=horarios.stream().sorted(comparadorTurnos()).map(t->t.getDiaSemana()+" "+t.getHoraInicio()+"-"+t.getHoraFin()+" ("+t.getGrupo().getNombre()+")").reduce((a,b)->a+"; "+b).orElse("");return nombreDeporte(deporte)+" · "+hs;}
 private Comparator<Grupo> comparadorGrupos(){return Comparator.comparingInt((Grupo g)->Optional.ofNullable(g.getRangoEdadMin()).orElse(0)).thenComparingInt(g->Optional.ofNullable(g.getRangoEdadMax()).orElse(99)).thenComparingInt(this::primerDiaGrupo).thenComparing(this::primeraHoraGrupo).thenComparing(Grupo::getId);}
 private int primerDiaGrupo(Grupo g){return turnos.findByGrupo(g).stream().mapToInt(t->ordenDia(t.getDiaSemana())).min().orElse(99);}
 private String primeraHoraGrupo(Grupo g){return turnos.findByGrupo(g).stream().map(Turno::getHoraInicio).filter(h->h!=null&&!h.isBlank()).min(String::compareTo).orElse("99:99");}
 private Comparator<Turno> comparadorTurnos(){return Comparator.comparingInt((Turno t)->ordenDia(t.getDiaSemana())).thenComparing(Turno::getHoraInicio);}
 private int ordenDia(String dia){return switch(normalizar(dia)){case "lunes"->1;case "martes"->2;case "miercoles"->3;case "jueves"->4;case "viernes"->5;case "sabado"->6;case "domingo"->7;default->99;};}
 private String referencia(){return "PRE-"+LocalDate.now().getYear()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();} private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private String hashIdempotencia(String value){if(blank(value))return null;String normalizada=value.trim();if(normalizada.length()>128||!normalizada.matches("[A-Za-z0-9._:-]+"))throw new IllegalArgumentException("La clave de idempotencia no tiene un formato válido.");return hash(normalizada);}
 private PreinscripcionDuplicadaException duplicada(){return new PreinscripcionDuplicadaException(MENSAJE_DUPLICADA);} private PreinscripcionDuplicadaException duplicada(Throwable cause){PreinscripcionDuplicadaException error=duplicada();error.initCause(cause);return error;}
 private boolean esConflictoDuplicado(DataIntegrityViolationException error){Throwable causa=error;while(causa!=null){String mensaje=causa.getMessage();if(mensaje!=null){String normalizado=mensaje.toLowerCase(Locale.ROOT);if(normalizado.contains("uk_preinscripcion_activa")||normalizado.contains("uk_preinscripcion_idempotencia"))return true;}causa=causa.getCause();}return false;}
 private String clean(String s){return s==null?null:s.replaceAll("[<>]","").trim();} private String limpiarObservacion(String s){return blank(s)?null:s.trim();} private boolean blank(String s){return s==null||s.isBlank();} private Object parse(String s){try{return json.readTree(s);}catch(Exception e){return s;}} private void jsonValido(String s){try{json.readTree(s);}catch(Exception e){throw new IllegalArgumentException("El contenido debe ser JSON válido.");}}
 private String esc(String value){return value==null?"":value.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
}
