import { AfterViewInit, Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common'; import { FormControl,FormGroup,ReactiveFormsModule,Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router'; import { ConfiguracionPreinscripcion, ContenidoPreinscripcion, PreinscripcionService } from '../../../features/preinscripcion/preinscripcion.service';

@Component({selector:'app-preinscripcion',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink],templateUrl:'./preinscripcion.component.html',styleUrl:'./preinscripcion.component.scss'})
export class PreinscripcionComponent implements OnInit, AfterViewInit {
 @ViewChild('firma') canvas?:ElementRef<HTMLCanvasElement>; temporada=''; grupos:any[]=[]; configuracion?:ConfiguracionPreinscripcion&{contenido:ContenidoPreinscripcion}; cargandoGrupos=false; cargandoNormas=false; errorNormas=''; errorHorarios=''; enviando=false; resultado:any; error=''; firmada=false; dibujando=false;
 readonly deportes=[['TAEKWONDO','Taekwondo'],['KICKBOXING','Kickboxing'],['PILATES','Pilates'],['DEFENSA_PERSONAL_FEMENINA','Defensa personal femenina']];
 readonly form=new FormGroup({deporte:new FormControl('',{nonNullable:true,validators:Validators.required}),turnoIds:new FormControl<number[]>([],{nonNullable:true,validators:Validators.required}),nombre:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(100)]}),apellidos:new FormControl('',{nonNullable:true,validators:Validators.required}),dni:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.pattern(/^[0-9XYZ][0-9]{7}[A-Z]$/i)]}),fechaNacimiento:new FormControl('',{nonNullable:true,validators:Validators.required}),direccion:new FormControl('',{nonNullable:true,validators:Validators.required}),telefono:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.pattern(/^(?:(?:\+|00)34[ ]*)?[6789](?:[ ]*\d){8}$/)]}),telefono2:new FormControl('',{nonNullable:true,validators:Validators.pattern(/^(?:(?:\+|00)34[ ]*)?[6789](?:[ ]*\d){8}$/)}),email:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.email]}),observaciones:new FormControl('',{nonNullable:true,validators:Validators.maxLength(1000)}),tutorNombre:new FormControl('',{nonNullable:true}),tutorDni:new FormControl('',{nonNullable:true}),tieneDiscapacidad:new FormControl<boolean|null>(null,Validators.required),consentimientoFotografico:new FormControl(false,{nonNullable:true}),aceptacionNormas:new FormControl({value:false,disabled:true},{nonNullable:true,validators:Validators.requiredTrue}),firmanteNombre:new FormControl('',{nonNullable:true,validators:Validators.required})});
 private turnoIdSolicitado:number|null=null; private grupoIdSolicitado:number|null=null;
 constructor(private readonly api:PreinscripcionService,private readonly route:ActivatedRoute){api.temporada().subscribe(x=>{this.temporada=x.temporada;this.revalidarTurnos();});}
 ngOnInit(){this.form.controls.fechaNacimiento.valueChanges.subscribe(()=>{this.actualizarValidacionIdentidad();this.revalidarTurnos();});this.actualizarValidacionIdentidad();const deporte=this.route.snapshot.queryParamMap.get('deporte'),turnoId=Number(this.route.snapshot.queryParamMap.get('turnoId')),grupoId=Number(this.route.snapshot.queryParamMap.get('grupoId'));if(deporte&&this.deportes.some(d=>d[0]===deporte)){this.form.controls.deporte.setValue(deporte);this.turnoIdSolicitado=Number.isSafeInteger(turnoId)&&turnoId>0?turnoId:null;this.grupoIdSolicitado=Number.isSafeInteger(grupoId)&&grupoId>0?grupoId:null;this.cambiarDeporte();}}
 ngAfterViewInit(){this.prepararCanvas();}
 cambiarDeporte(){const deporte=this.form.controls.deporte.value;this.form.controls.turnoIds.setValue([]);this.form.controls.aceptacionNormas.reset({value:false,disabled:true});this.grupos=[];this.configuracion=undefined;this.errorNormas='';this.errorHorarios='';if(!deporte){this.cargandoGrupos=false;this.cargandoNormas=false;return;}this.cargandoGrupos=true;this.cargandoNormas=true;this.api.grupos(deporte).subscribe({next:x=>{this.grupos=x;this.cargandoGrupos=false;this.revalidarTurnos();},error:()=>{this.grupos=[];this.turnoIdSolicitado=null;this.grupoIdSolicitado=null;this.cargandoGrupos=false;}});this.api.configuracion(deporte).subscribe({next:x=>this.cargarConfiguracion(x),error:()=>{this.cargandoNormas=false;this.errorNormas='No se pudieron cargar las normas. Cambia de actividad o inténtalo de nuevo.';}});}
 get gruposCompatibles(){const edad=this.edadCohorte();if(edad===null)return [];return this.grupos.filter(g=>edad>=(g.rangoEdadMin??0)&&edad<=(g.rangoEdadMax??99));}
 get turnosSeleccionados(){const ids=new Set(this.form.controls.turnoIds.value);return this.grupos.flatMap(g=>(g.turnos||[]).map((t:any)=>({...t,grupo:g}))).filter((t:any)=>ids.has(t.id));}
 turnoSeleccionado(id:number){return this.form.controls.turnoIds.value.includes(id);}
 alternarTurno(turno:any,marcado:boolean){let ids=this.form.controls.turnoIds.value.filter(id=>id!==turno.id);if(marcado){const mismoDia=new Set(this.grupos.flatMap(g=>g.turnos||[]).filter((t:any)=>this.normalizarDia(t.diaSemana)===this.normalizarDia(turno.diaSemana)).map((t:any)=>t.id));ids=ids.filter(id=>!mismoDia.has(id));ids.push(turno.id);}this.form.controls.turnoIds.setValue(ids);this.form.controls.turnoIds.markAsTouched();this.errorHorarios='';}
 private revalidarTurnos(){if(this.edadCohorte()===null||this.cargandoGrupos)return;const validos=new Set(this.gruposCompatibles.flatMap(g=>(g.turnos||[]).map((t:any)=>t.id)));if(this.turnoIdSolicitado!==null){const turnoId=this.turnoIdSolicitado;this.form.controls.turnoIds.setValue(validos.has(turnoId)?[turnoId]:[]);if(!validos.has(turnoId))this.errorHorarios='Turno enlazado no está disponible o no es compatible con edad indicada.';this.turnoIdSolicitado=null;this.grupoIdSolicitado=null;}else if(this.grupoIdSolicitado!==null){const grupo=this.gruposCompatibles.find(g=>g.id===this.grupoIdSolicitado);this.form.controls.turnoIds.setValue(grupo?this.idsUnicosPorDia(grupo.turnos||[]):[]);if(!grupo)this.errorHorarios='Grupo enlazado no es compatible con edad indicada.';this.grupoIdSolicitado=null;}const actuales=this.form.controls.turnoIds.value,nuevos=actuales.filter(id=>validos.has(id));if(nuevos.length!==actuales.length){this.form.controls.turnoIds.setValue(nuevos);this.errorHorarios='Se han quitado horarios que no son compatibles con edad indicada.';}}
 private idsUnicosPorDia(turnos:any[]){const dias=new Set<string>();return turnos.filter(t=>{const dia=this.normalizarDia(t.diaSemana);if(dias.has(dia))return false;dias.add(dia);return true;}).map(t=>t.id);}
 private edadCohorte(){const valor=this.form.controls.fechaNacimiento.value,inicio=Number.parseInt(this.temporada.slice(0,4),10),nacimiento=Number.parseInt(valor.slice(0,4),10);if(!/^\d{4}-\d{2}-\d{2}$/.test(valor)||!/^\d{4}-\d{4}$/.test(this.temporada)||!Number.isInteger(inicio)||!Number.isInteger(nacimiento))return null;return inicio-nacimiento;}
 private normalizarDia(dia:string){return (dia||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
 iniciar(e:PointerEvent){this.dibujando=true;(e.target as HTMLElement).setPointerCapture(e.pointerId);this.trazar(e,true);} mover(e:PointerEvent){if(this.dibujando)this.trazar(e,false);} terminar(){this.dibujando=false;this.firmada=true;}
 limpiarFirma(){const c=this.canvas?.nativeElement;if(c){const ctx=c.getContext('2d');if(ctx){ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.restore();}}this.firmada=false;}
 enviar(){if(!this.normasDisponibles||this.form.invalid||!this.firmada){this.form.markAllAsTouched();this.error=this.normasDisponibles?'Revisa los campos obligatorios y añade la firma.':'No puedes enviar la solicitud hasta que se carguen las normas.';return;}this.error='';this.enviando=true;const firmaBase64=this.canvas!.nativeElement.toDataURL('image/png');this.api.crear({...this.form.getRawValue(),firmaBase64}).subscribe({next:r=>{this.resultado=r;this.enviando=false;requestAnimationFrame(()=>globalThis.window?.scrollTo({top:0,behavior:'smooth'}));},error:e=>{this.error=e?.error?.message||e?.error?.mensaje||'No se pudo enviar la preinscripción.';this.enviando=false;}});}
 descargar(){location.href=`${(this.api as any).base}/${this.resultado.referencia}/documento?token=${encodeURIComponent(this.resultado.tokenDocumento)}`;}
 esMenor(){const f=this.form.controls.fechaNacimiento.value;if(!f)return false;const d=new Date(f);const hoy=new Date();let edad=hoy.getFullYear()-d.getFullYear();if(hoy < new Date(hoy.getFullYear(),d.getMonth(),d.getDate()))edad--;return edad<18;}
 private actualizarValidacionIdentidad(){const patron=Validators.pattern(/^[0-9XYZ][0-9]{7}[A-Z]$/i);this.form.controls.dni.setValidators(this.esMenor()?[patron]:[Validators.required,patron]);this.form.controls.tutorNombre.setValidators(this.esMenor()?[Validators.required,Validators.maxLength(180)]:[]);this.form.controls.tutorDni.setValidators(this.esMenor()?[Validators.required,patron]:[]);this.form.controls.dni.updateValueAndValidity({emitEvent:false});this.form.controls.tutorNombre.updateValueAndValidity({emitEvent:false});this.form.controls.tutorDni.updateValueAndValidity({emitEvent:false});}
 get normasDisponibles(){return Boolean(this.configuracion?.contenido.normas.length);}
 comprobarLecturaNormas(elemento:HTMLElement){if(elemento.scrollTop+elemento.clientHeight>=elemento.scrollHeight-4)this.form.controls.aceptacionNormas.enable();}
 private cargarConfiguracion(respuesta:ConfiguracionPreinscripcion){try{const contenido=typeof respuesta.contenido==='string'?JSON.parse(respuesta.contenido):respuesta.contenido;const normas=Array.isArray(contenido?.normas)?contenido.normas.filter((n:unknown):n is string=>typeof n==='string'&&n.trim().length>0):[];if(!normas.length)throw new Error('Sin normas');this.configuracion={...respuesta,contenido:{...contenido,normas}};requestAnimationFrame(()=>{const elemento=document.querySelector<HTMLElement>('.rules-content');if(elemento)this.comprobarLecturaNormas(elemento);});}catch{this.configuracion=undefined;this.errorNormas='Las normas publicadas no tienen un formato válido. Inténtalo de nuevo más tarde.';}finally{this.cargandoNormas=false;}}
 private prepararCanvas(){const c=this.canvas?.nativeElement;if(!c)return;const rect=c.getBoundingClientRect();c.width=Math.max(600,rect.width*2);c.height=220;const ctx=c.getContext('2d');if(ctx){ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.scale(c.width/Math.max(rect.width,1),2);ctx.lineWidth=2;ctx.lineCap='round';ctx.strokeStyle='#172126';}}
 private trazar(e:PointerEvent,inicio:boolean){const c=this.canvas!.nativeElement,ctx=c.getContext('2d')!,r=c.getBoundingClientRect();const x=e.clientX-r.left,y=e.clientY-r.top;if(inicio){ctx.beginPath();ctx.moveTo(x,y);}else{ctx.lineTo(x,y);ctx.stroke();}}
}
