import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common'; import { FormControl,FormGroup,ReactiveFormsModule,Validators } from '@angular/forms';
import { RouterLink } from '@angular/router'; import { PreinscripcionService } from '../../../features/preinscripcion/preinscripcion.service';

@Component({selector:'app-preinscripcion',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink],templateUrl:'./preinscripcion.component.html',styleUrl:'./preinscripcion.component.scss'})
export class PreinscripcionComponent implements AfterViewInit {
 @ViewChild('firma') canvas?:ElementRef<HTMLCanvasElement>; temporada=''; grupos:any[]=[]; configuracion:any; enviando=false; resultado:any; error=''; firmada=false; dibujando=false;
 readonly deportes=[['TAEKWONDO','Taekwondo'],['KICKBOXING','Kickboxing'],['PILATES','Pilates'],['DEFENSA_PERSONAL_FEMENINA','Defensa personal femenina']];
 readonly form=new FormGroup({deporte:new FormControl('',{nonNullable:true,validators:Validators.required}),grupoId:new FormControl<number|null>(null,Validators.required),nombre:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(100)]}),apellidos:new FormControl('',{nonNullable:true,validators:Validators.required}),dni:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.pattern(/^[0-9XYZ][0-9]{7}[A-Z]$/i)]}),fechaNacimiento:new FormControl('',{nonNullable:true,validators:Validators.required}),direccion:new FormControl('',{nonNullable:true,validators:Validators.required}),telefono:new FormControl('',{nonNullable:true,validators:Validators.required}),email:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.email]}),tutorNombre:new FormControl('',{nonNullable:true}),tutorDni:new FormControl('',{nonNullable:true}),consentimientoFotografico:new FormControl(false,{nonNullable:true}),aceptacionNormas:new FormControl(false,{nonNullable:true,validators:Validators.requiredTrue}),firmanteNombre:new FormControl('',{nonNullable:true,validators:Validators.required})});
 constructor(private readonly api:PreinscripcionService){api.temporada().subscribe(x=>this.temporada=x.temporada);}
 ngAfterViewInit(){this.prepararCanvas();}
 cambiarDeporte(){const deporte=this.form.controls.deporte.value;this.form.controls.grupoId.setValue(null);this.api.grupos(deporte).subscribe(x=>this.grupos=x);this.api.configuracion(deporte).subscribe(x=>this.configuracion=x);}
 iniciar(e:PointerEvent){this.dibujando=true;(e.target as HTMLElement).setPointerCapture(e.pointerId);this.trazar(e,true);} mover(e:PointerEvent){if(this.dibujando)this.trazar(e,false);} terminar(){this.dibujando=false;this.firmada=true;}
 limpiarFirma(){const c=this.canvas?.nativeElement;if(c){const ctx=c.getContext('2d');if(ctx){ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.restore();}}this.firmada=false;}
 enviar(){if(this.form.invalid||!this.firmada){this.form.markAllAsTouched();this.error='Revisa los campos obligatorios y añade la firma.';return;}this.error='';this.enviando=true;const firmaBase64=this.canvas!.nativeElement.toDataURL('image/png');this.api.crear({...this.form.getRawValue(),firmaBase64}).subscribe({next:r=>{this.resultado=r;this.enviando=false;},error:e=>{this.error=e?.error?.message||e?.error?.mensaje||'No se pudo enviar la preinscripción.';this.enviando=false;}});}
 descargar(){location.href=`${(this.api as any).base}/${this.resultado.referencia}/documento?token=${encodeURIComponent(this.resultado.tokenDocumento)}`;}
 esMenor(){const f=this.form.controls.fechaNacimiento.value;if(!f)return false;const d=new Date(f);const hoy=new Date();let edad=hoy.getFullYear()-d.getFullYear();if(hoy < new Date(hoy.getFullYear(),d.getMonth(),d.getDate()))edad--;return edad<18;}
 private prepararCanvas(){const c=this.canvas?.nativeElement;if(!c)return;const rect=c.getBoundingClientRect();c.width=Math.max(600,rect.width*2);c.height=220;const ctx=c.getContext('2d');if(ctx){ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.scale(c.width/Math.max(rect.width,1),2);ctx.lineWidth=2;ctx.lineCap='round';ctx.strokeStyle='#172126';}}
 private trazar(e:PointerEvent,inicio:boolean){const c=this.canvas!.nativeElement,ctx=c.getContext('2d')!,r=c.getBoundingClientRect();const x=e.clientX-r.left,y=e.clientY-r.top;if(inicio){ctx.beginPath();ctx.moveTo(x,y);}else{ctx.lineTo(x,y);ctx.stroke();}}
}
