import { AfterViewInit, Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common'; import { FormControl,FormGroup,ReactiveFormsModule,Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router'; import { ConfiguracionPreinscripcion, ContenidoPreinscripcion, PreinscripcionService } from '../../../features/preinscripcion/preinscripcion.service';

@Component({selector:'app-preinscripcion',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink],templateUrl:'./preinscripcion.component.html',styleUrl:'./preinscripcion.component.scss'})
export class PreinscripcionComponent implements OnInit, AfterViewInit {
 @ViewChild('firma') canvas?:ElementRef<HTMLCanvasElement>; temporada=''; grupos:any[]=[]; configuracion?:ConfiguracionPreinscripcion&{contenido:ContenidoPreinscripcion}; cargandoGrupos=false; cargandoNormas=false; errorNormas=''; enviando=false; resultado:any; error=''; firmada=false; dibujando=false;
 readonly deportes=[['TAEKWONDO','Taekwondo'],['KICKBOXING','Kickboxing'],['PILATES','Pilates'],['DEFENSA_PERSONAL_FEMENINA','Defensa personal femenina']];
 readonly form=new FormGroup({deporte:new FormControl('',{nonNullable:true,validators:Validators.required}),grupoId:new FormControl<number|null>(null,Validators.required),nombre:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(100)]}),apellidos:new FormControl('',{nonNullable:true,validators:Validators.required}),dni:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.pattern(/^[0-9XYZ][0-9]{7}[A-Z]$/i)]}),fechaNacimiento:new FormControl('',{nonNullable:true,validators:Validators.required}),direccion:new FormControl('',{nonNullable:true,validators:Validators.required}),telefono:new FormControl('',{nonNullable:true,validators:Validators.required}),email:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.email]}),tutorNombre:new FormControl('',{nonNullable:true}),tutorDni:new FormControl('',{nonNullable:true}),consentimientoFotografico:new FormControl(false,{nonNullable:true}),aceptacionNormas:new FormControl({value:false,disabled:true},{nonNullable:true,validators:Validators.requiredTrue}),firmanteNombre:new FormControl('',{nonNullable:true,validators:Validators.required})});
 private grupoIdSolicitado:number|null=null;
 constructor(private readonly api:PreinscripcionService,private readonly route:ActivatedRoute){api.temporada().subscribe(x=>this.temporada=x.temporada);}
 ngOnInit(){const deporte=this.route.snapshot.queryParamMap.get('deporte');const grupoId=Number(this.route.snapshot.queryParamMap.get('grupoId'));if(deporte&&this.deportes.some(d=>d[0]===deporte)){this.form.controls.deporte.setValue(deporte);this.grupoIdSolicitado=Number.isSafeInteger(grupoId)&&grupoId>0?grupoId:null;this.cambiarDeporte();}}
 ngAfterViewInit(){this.prepararCanvas();}
 cambiarDeporte(){const deporte=this.form.controls.deporte.value;this.form.controls.grupoId.setValue(null);this.form.controls.aceptacionNormas.reset({value:false,disabled:true});this.grupos=[];this.configuracion=undefined;this.errorNormas='';if(!deporte){this.cargandoGrupos=false;this.cargandoNormas=false;return;}this.cargandoGrupos=true;this.cargandoNormas=true;this.api.grupos(deporte).subscribe({next:x=>{this.grupos=x;const solicitado=this.grupoIdSolicitado;if(solicitado!==null&&x.some(g=>g.id===solicitado)){this.form.controls.grupoId.setValue(solicitado);}this.grupoIdSolicitado=null;this.cargandoGrupos=false;},error:()=>{this.grupos=[];this.grupoIdSolicitado=null;this.cargandoGrupos=false;}});this.api.configuracion(deporte).subscribe({next:x=>this.cargarConfiguracion(x),error:()=>{this.cargandoNormas=false;this.errorNormas='No se pudieron cargar las normas. Cambia de actividad o inténtalo de nuevo.';}});}
 iniciar(e:PointerEvent){this.dibujando=true;(e.target as HTMLElement).setPointerCapture(e.pointerId);this.trazar(e,true);} mover(e:PointerEvent){if(this.dibujando)this.trazar(e,false);} terminar(){this.dibujando=false;this.firmada=true;}
 limpiarFirma(){const c=this.canvas?.nativeElement;if(c){const ctx=c.getContext('2d');if(ctx){ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.restore();}}this.firmada=false;}
 enviar(){if(!this.normasDisponibles||this.form.invalid||!this.firmada){this.form.markAllAsTouched();this.error=this.normasDisponibles?'Revisa los campos obligatorios y añade la firma.':'No puedes enviar la solicitud hasta que se carguen las normas.';return;}this.error='';this.enviando=true;const firmaBase64=this.canvas!.nativeElement.toDataURL('image/png');this.api.crear({...this.form.getRawValue(),firmaBase64}).subscribe({next:r=>{this.resultado=r;this.enviando=false;requestAnimationFrame(()=>globalThis.window?.scrollTo({top:0,behavior:'smooth'}));},error:e=>{this.error=e?.error?.message||e?.error?.mensaje||'No se pudo enviar la preinscripción.';this.enviando=false;}});}
 descargar(){location.href=`${(this.api as any).base}/${this.resultado.referencia}/documento?token=${encodeURIComponent(this.resultado.tokenDocumento)}`;}
 esMenor(){const f=this.form.controls.fechaNacimiento.value;if(!f)return false;const d=new Date(f);const hoy=new Date();let edad=hoy.getFullYear()-d.getFullYear();if(hoy < new Date(hoy.getFullYear(),d.getMonth(),d.getDate()))edad--;return edad<18;}
 get normasDisponibles(){return Boolean(this.configuracion?.contenido.normas.length);}
 comprobarLecturaNormas(elemento:HTMLElement){if(elemento.scrollTop+elemento.clientHeight>=elemento.scrollHeight-4)this.form.controls.aceptacionNormas.enable();}
 private cargarConfiguracion(respuesta:ConfiguracionPreinscripcion){try{const contenido=typeof respuesta.contenido==='string'?JSON.parse(respuesta.contenido):respuesta.contenido;const normas=Array.isArray(contenido?.normas)?contenido.normas.filter((n:unknown):n is string=>typeof n==='string'&&n.trim().length>0):[];if(!normas.length)throw new Error('Sin normas');this.configuracion={...respuesta,contenido:{...contenido,normas}};requestAnimationFrame(()=>{const elemento=document.querySelector<HTMLElement>('.rules-content');if(elemento)this.comprobarLecturaNormas(elemento);});}catch{this.configuracion=undefined;this.errorNormas='Las normas publicadas no tienen un formato válido. Inténtalo de nuevo más tarde.';}finally{this.cargandoNormas=false;}}
 private prepararCanvas(){const c=this.canvas?.nativeElement;if(!c)return;const rect=c.getBoundingClientRect();c.width=Math.max(600,rect.width*2);c.height=220;const ctx=c.getContext('2d');if(ctx){ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.scale(c.width/Math.max(rect.width,1),2);ctx.lineWidth=2;ctx.lineCap='round';ctx.strokeStyle='#172126';}}
 private trazar(e:PointerEvent,inicio:boolean){const c=this.canvas!.nativeElement,ctx=c.getContext('2d')!,r=c.getBoundingClientRect();const x=e.clientX-r.left,y=e.clientY-r.top;if(inicio){ctx.beginPath();ctx.moveTo(x,y);}else{ctx.lineTo(x,y);ctx.stroke();}}
}
