-- MySQL Script generated by MySQL Workbench
-- Sat Apr  6 14:12:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema taemoidb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taemoidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taemoidb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `taemoidb` ;

-- -----------------------------------------------------
-- Table `taemoidb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_categoria` ENUM('PRETKD', 'INFANTIL', 'PRECADETE', 'CADETE', 'JUNIOR', 'SUB21', 'SENIOR') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`grado` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo_grado` ENUM('BLANCO', 'BLANCO_AMARILLO', 'AMARILLO', 'AMARILLO_NARANJA', 'NARANJA', 'NARANJA_VERDE', 'VERDE', 'VERDE_AZUL', 'AZUL', 'AZUL_ROJO', 'ROJO', 'ROJO_NEGRO', 'NEGRO') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`alumno` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `apellidos` VARCHAR(255) NULL DEFAULT NULL,
  `cuantia_tarifa` DOUBLE NOT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_alta` DATE NULL DEFAULT NULL,
  `fecha_baja` DATE NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `nif` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `numero_expediente` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` INT NOT NULL,
  `tipo_tarifa` ENUM('ADULTO', 'ADULTO_GRUPO', 'FAMILIAR', 'INFANTIL', 'INFANTIL_GRUPO', 'HERMANOS', 'PADRES_HIJOS') NOT NULL,
  `categoria_id` BIGINT NULL DEFAULT NULL,
  `grado_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_i2otd4eccxkj7jwqeygr3wgoj` (`numero_expediente` ASC) VISIBLE,
  INDEX `FK3sss574xtkjpgdljygxm19glf` (`categoria_id` ASC) VISIBLE,
  INDEX `FKid01ntlqpypy38pi2bk0nlof3` (`grado_id` ASC) VISIBLE,
  CONSTRAINT `FK3sss574xtkjpgdljygxm19glf`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `taemoidb`.`categoria` (`id`),
  CONSTRAINT `FKid01ntlqpypy38pi2bk0nlof3`
    FOREIGN KEY (`grado_id`)
    REFERENCES `taemoidb`.`grado` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 221
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`examen` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `alumno_id` BIGINT NULL DEFAULT NULL,
  `examen_grado_id` BIGINT NULL DEFAULT NULL,
  `grado_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKfpng0mexxc3pejhtus8lvn65o` (`alumno_id` ASC) VISIBLE,
  INDEX `FKg7lpgnjshqpi2ovn0qw1moo3m` (`examen_grado_id` ASC) VISIBLE,
  INDEX `FKgjt7f8vr2l4syxewdxjia50c0` (`grado_id` ASC) VISIBLE,
  CONSTRAINT `FKfpng0mexxc3pejhtus8lvn65o`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `taemoidb`.`alumno` (`id`),
  CONSTRAINT `FKg7lpgnjshqpi2ovn0qw1moo3m`
    FOREIGN KEY (`examen_grado_id`)
    REFERENCES `taemoidb`.`grado` (`id`),
  CONSTRAINT `FKgjt7f8vr2l4syxewdxjia50c0`
    FOREIGN KEY (`grado_id`)
    REFERENCES `taemoidb`.`grado` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`foto_alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`foto_alumno` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alumno_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKc7vld6hhv52csq4yw5vbgscl3` (`alumno_id` ASC) VISIBLE,
  CONSTRAINT `FKc7vld6hhv52csq4yw5vbgscl3`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `taemoidb`.`alumno` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`grupo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(255) NULL DEFAULT NULL,
  `dia_semana` INT NOT NULL,
  `hora_fin` VARCHAR(255) NULL DEFAULT NULL,
  `hora_inicio` VARCHAR(255) NULL DEFAULT NULL,
  `numero_expediente_alumno` VARCHAR(255) NULL DEFAULT NULL,
  `turno` VARCHAR(255) NULL DEFAULT NULL,
  `alumno_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKlvr29ivbtky4v7q0ck6nhkvaw` (`alumno_id` ASC) VISIBLE,
  CONSTRAINT `FKlvr29ivbtky4v7q0ck6nhkvaw`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `taemoidb`.`alumno` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`pago` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `concepto` VARCHAR(255) NULL DEFAULT NULL,
  `cuantia` DOUBLE NOT NULL,
  `estado` ENUM('PAGADO', 'NO_PAGADO') NOT NULL,
  `fecha` DATE NOT NULL,
  `numero_expediente_alumno` VARCHAR(255) NULL DEFAULT NULL,
  `alumno_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKaxf1p403r03amcvwbacx9rusq` (`alumno_id` ASC) VISIBLE,
  CONSTRAINT `FKaxf1p403r03amcvwbacx9rusq`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `taemoidb`.`alumno` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `apellidos` VARCHAR(255) NULL DEFAULT NULL,
  `contrasena` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_5171l57faosmj8myawaucatdw` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`usuario_rol` (
  `usuario_id` BIGINT NOT NULL,
  `roles` ENUM('ROLE_USER', 'ROLE_ADMIN') NULL DEFAULT NULL,
  INDEX `FKbyfgloj439r9wr9smrms9u33r` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `FKbyfgloj439r9wr9smrms9u33r`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `taemoidb`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
