-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 16:19:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema taemoidb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taemoidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taemoidb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `taemoidb` ;

-- -----------------------------------------------------
-- Table `taemoidb`.`imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`imagen` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `datos` LONGBLOB NOT NULL,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `tipo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_categoria` ENUM('CADETE', 'INFANTIL', 'JUNIOR', 'PRECADETE', 'PRETKD', 'SENIOR', 'SUB21') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`grado` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo_grado` ENUM('AMARILLO', 'AMARILLO_NARANJA', 'AZUL', 'AZUL_ROJO', 'BLANCO', 'BLANCO_AMARILLO', 'NARANJA', 'NARANJA_VERDE', 'NEGRO', 'ROJO', 'ROJO_NEGRO', 'VERDE', 'VERDE_AZUL') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`alumno` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `apellidos` VARCHAR(255) NULL DEFAULT NULL,
  `cuantia_tarifa` DOUBLE NOT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_alta` DATE NULL DEFAULT NULL,
  `fecha_baja` DATE NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `nif` VARCHAR(9) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `numero_expediente` INT NOT NULL,
  `telefono` INT NOT NULL,
  `tipo_tarifa` ENUM('ADULTO', 'ADULTO_GRUPO', 'FAMILIAR', 'HERMANOS', 'INFANTIL', 'INFANTIL_GRUPO', 'PADRES_HIJOS') NOT NULL,
  `categoria_id` BIGINT NULL DEFAULT NULL,
  `foto_alumno_id` BIGINT NULL DEFAULT NULL,
  `grado_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_i2otd4eccxkj7jwqeygr3wgoj` (`numero_expediente` ASC) VISIBLE,
  UNIQUE INDEX `UK_juke9njf11mdvhyauigofa3g2` (`foto_alumno_id` ASC) VISIBLE,
  INDEX `FK3sss574xtkjpgdljygxm19glf` (`categoria_id` ASC) VISIBLE,
  INDEX `FKid01ntlqpypy38pi2bk0nlof3` (`grado_id` ASC) VISIBLE,
  CONSTRAINT `FK35h62thngrq0o15s2www7u451`
    FOREIGN KEY (`foto_alumno_id`)
    REFERENCES `taemoidb`.`imagen` (`id`),
  CONSTRAINT `FK3sss574xtkjpgdljygxm19glf`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `taemoidb`.`categoria` (`id`),
  CONSTRAINT `FKid01ntlqpypy38pi2bk0nlof3`
    FOREIGN KEY (`grado_id`)
    REFERENCES `taemoidb`.`grado` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`grupo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`alumno_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`alumno_grupo` (
  `grupo_id` BIGINT NOT NULL,
  `alumno_id` BIGINT NOT NULL,
  INDEX `FK9m58u5wqf6fc2i5qur535qic6` (`alumno_id` ASC) VISIBLE,
  INDEX `FKc3q87xf5n31xgpfun4b7jndg0` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `FK9m58u5wqf6fc2i5qur535qic6`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `taemoidb`.`alumno` (`id`),
  CONSTRAINT `FKc3q87xf5n31xgpfun4b7jndg0`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `taemoidb`.`grupo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`evento` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  `foto_evento_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_4181ienduxeq2ridhuwd3qvwk` (`foto_evento_id` ASC) VISIBLE,
  CONSTRAINT `FK8r4xhbhw72x5gsalwsmf6km67`
    FOREIGN KEY (`foto_evento_id`)
    REFERENCES `taemoidb`.`imagen` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`examen` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `alumno_id` BIGINT NULL DEFAULT NULL,
  `examen_grado_id` BIGINT NULL DEFAULT NULL,
  `grado_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKfpng0mexxc3pejhtus8lvn65o` (`alumno_id` ASC) VISIBLE,
  INDEX `FKg7lpgnjshqpi2ovn0qw1moo3m` (`examen_grado_id` ASC) VISIBLE,
  INDEX `FKgjt7f8vr2l4syxewdxjia50c0` (`grado_id` ASC) VISIBLE,
  CONSTRAINT `FKfpng0mexxc3pejhtus8lvn65o`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `taemoidb`.`alumno` (`id`),
  CONSTRAINT `FKg7lpgnjshqpi2ovn0qw1moo3m`
    FOREIGN KEY (`examen_grado_id`)
    REFERENCES `taemoidb`.`grado` (`id`),
  CONSTRAINT `FKgjt7f8vr2l4syxewdxjia50c0`
    FOREIGN KEY (`grado_id`)
    REFERENCES `taemoidb`.`grado` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`pago` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `concepto` VARCHAR(255) NULL DEFAULT NULL,
  `cuantia` DOUBLE NOT NULL,
  `estado` ENUM('NO_PAGADO', 'PAGADO') NOT NULL,
  `fecha` DATE NOT NULL,
  `numero_expediente_alumno` VARCHAR(255) NULL DEFAULT NULL,
  `alumno_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKaxf1p403r03amcvwbacx9rusq` (`alumno_id` ASC) VISIBLE,
  CONSTRAINT `FKaxf1p403r03amcvwbacx9rusq`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `taemoidb`.`alumno` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`turno` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `dia_semana` VARCHAR(255) NULL DEFAULT NULL,
  `hora_fin` VARCHAR(255) NULL DEFAULT NULL,
  `hora_inicio` VARCHAR(255) NULL DEFAULT NULL,
  `grupo_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKp5gxotvxjlr365k51g04k28ar` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `FKp5gxotvxjlr365k51g04k28ar`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `taemoidb`.`grupo` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `apellidos` VARCHAR(50) NULL DEFAULT NULL,
  `contrasena` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `alumno_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_5171l57faosmj8myawaucatdw` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UK_iwqbs97sir17hipge3olmu6i6` (`alumno_id` ASC) VISIBLE,
  CONSTRAINT `FKs2jdpk0wmqgyj2i2jer600y8b`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `taemoidb`.`alumno` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `taemoidb`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taemoidb`.`usuario_rol` (
  `usuario_id` BIGINT NOT NULL,
  `roles` ENUM('ROLE_ADMIN', 'ROLE_MANAGER', 'ROLE_USER') NULL DEFAULT NULL,
  INDEX `FKbyfgloj439r9wr9smrms9u33r` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `FKbyfgloj439r9wr9smrms9u33r`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `taemoidb`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
