spring.datasource.url=${SPRING_DATASOURCE_URL_DOCKER}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Base URL for serving images and documents (from environment variable)
app.base.url=${APP_BASE_URL:http://localhost}

# Frontend URL for password reset links
app.frontend.base-url=${APP_FRONTEND_BASE_URL:https://moiskimdo.es}
